### ISSUE TITLE
Browser Support Imformation

### ISSUE THREAD

**Issue by valmont** [sconsult/croppic#1]
Does this exist?

**Comment by sconsult** [comment]
With the release from today we are supporting the latest browser versions of IE, Chrome, FF Safari and Opera.
We are looking into IE8+ support but no decision has been made if and when we are working on those

**Comment by gbergamo** [comment]
Hi, There´s a solution for IE8+ ?

**Comment by sconsult** [comment]
Hi,

There have been attempts to solve it and I believe if you modify the code provided here you can make it work.

https://github.com/sconsult/croppic/pull/30

We have currently no volunteer to integrate it into the master.

Cheers

Mat
