### ISSUE TITLE
Allow zoom out to get an image smaller than croppic container

### ISSUE THREAD

**Issue by leocorder** [sconsult/croppic#100]
I'm using this great plugin and it's going very well, but some users are complaining about the use restriction of the zoom out option: it is not possible get an image smaller than the croppic container.
I tried to improve the zoom function but did not succeed.
Is there some way to make this possible? Maybe some option could allow this behavior and then the save php function could fill the remaining area with some background color (white, i.e).

**Comment by sconsult** [comment]
hi @leocorder 

This request looks identical  to the Issue: https://github.com/sconsult/croppic/issues/92

There are two aspects, and please bare with me i just threw that quickly
![sample](https://cloud.githubusercontent.com/assets/10435334/7619466/de6f31d8-f986-11e4-938b-6343a673a228.jpg)
 together

Zoom function:

I have modified the zoom quickly to allow a factor x to be applied, x is the ratio of how much smaller then your original css defined crop field should be.

//default factor 1
var allowSmallerFactor =1;			
//checking if i am initializing the zoom, there are more elegant possibillities, but for the sake of it.
if(x !=40)
	allowSmallerFactor=3  //in case of not init, i allow a 3 times smaller picture.
if( newWidth*allowSmallerFactor < that.objW || newHeight*allowSmallerFactor < that.objH){
				
				if( newWidth - that.objW < newHeight - that.objH ){ 
					newWidth = that.objW/allowSmallerFactor;
					newHeight = newWidth/ratio;
				}else{
					newHeight = that.objH/allowSmallerFactor;
					newWidth = ratio * newHeight;
				}
				
				doPositioning = false;
				
			} 
			
			if(!that.options.scaleToFill && (newWidth*allowSmallerFactor > that.imgInitW || newHeight*allowSmallerFactor > that.imgInitH)){
				
				if( newWidth - that.imgInitW < newHeight - that.imgInitH ){ 
					newWidth = that.imgInitW/allowSmallerFactor;
					newHeight = newWidth/ratio;
				}else{
					newHeight = that.imgInitH/allowSmallerFactor;
					newWidth = ratio * newHeight;
				}
				
				doPositioning = false;
				
			}

Since the crop happens in the PHP file or in the programming language of your choosing you need to modify it there. default would be black as background for GD library (which im running)

Hope that helps

Mat

**Comment by leocorder** [comment]
Hi @sconsult 

That's exactly what I was looking for. Thanks for the support.
I have modified the PHP crop example file in order to attend both cases: cropped image smaller than defined crop field or not.
Look for changes before the final imagecopyresampled function. Here is the new code:

```php
<?php
/*
*	!!! THIS IS JUST AN EXAMPLE !!!, PLEASE USE ImageMagick or some other quality image processing libraries
*/
$imgUrl = $_POST['imgUrl'];
// original sizes
$imgInitW = $_POST['imgInitW'];
$imgInitH = $_POST['imgInitH'];
// resized sizes
$imgW = $_POST['imgW'];
$imgH = $_POST['imgH'];
// offsets
$imgY1 = $_POST['imgY1'];
$imgX1 = $_POST['imgX1'];
// crop box
$cropW = $_POST['cropW'];
$cropH = $_POST['cropH'];
// rotation angle
$angle = $_POST['rotation'];

$jpeg_quality = 100;

$output_filename = "temp/croppedImg_".rand();

// uncomment line below to save the cropped image in the same location as the original image.
//$output_filename = dirname($imgUrl). "/croppedImg_".rand();

$what = getimagesize($imgUrl);

switch(strtolower($what['mime']))
{
    case 'image/png':
        $img_r = imagecreatefrompng($imgUrl);
		$source_image = imagecreatefrompng($imgUrl);
		$type = '.png';
        break;
    case 'image/jpeg':
        $img_r = imagecreatefromjpeg($imgUrl);
		$source_image = imagecreatefromjpeg($imgUrl);
		error_log("jpg");
		$type = '.jpeg';
        break;
    case 'image/gif':
        $img_r = imagecreatefromgif($imgUrl);
		$source_image = imagecreatefromgif($imgUrl);
		$type = '.gif';
        break;
    default: die('image type not supported');
}


//Check write Access to Directory

if(!is_writable(dirname($output_filename))){
	$response = Array(
	    "status" => 'error',
	    "message" => 'Can`t write cropped File'
    );	
}else{

    // resize the original image to size of editor
    $resizedImage = imagecreatetruecolor($imgW, $imgH);
	imagecopyresampled($resizedImage, $source_image, 0, 0, 0, 0, $imgW, $imgH, $imgInitW, $imgInitH);
    // rotate the rezized image
    $rotated_image = imagerotate($resizedImage, -$angle, 0);
    // find new width & height of rotated image
    $rotated_width = imagesx($rotated_image);
    $rotated_height = imagesy($rotated_image);
    // diff between rotated & original sizes
    $dx = $rotated_width - $imgW;
    $dy = $rotated_height - $imgH;
    // crop rotated image to fit into original rezized rectangle
	$cropped_rotated_image = imagecreatetruecolor($imgW, $imgH);
	imagecolortransparent($cropped_rotated_image, imagecolorallocate($cropped_rotated_image, 0, 0, 0));
	imagecopyresampled($cropped_rotated_image, $rotated_image, 0, 0, $dx / 2, $dy / 2, $imgW, $imgH, $imgW, $imgH);
	// crop image into selected area
	$final_image = imagecreatetruecolor($cropW, $cropH);
	imagecolortransparent($final_image, imagecolorallocate($final_image, 0, 0, 0));
	// if image width is smaller than defined crop field or not
	if($imgW < $cropW){
        $dst_x = $imgX1;
        $dst_y = $imgY1;
        $src_x = $src_y = 0;
        $width = $imgW;
        $height = $imgH;
    }else{
        $dst_x = $dst_y = 0;
        $src_x = $imgX1;
        $src_y = $imgY1;
        $width = $cropW;
        $height = $cropH;
    }
	imagecopyresampled($final_image, $cropped_rotated_image, $dst_x, $dst_y, $src_x, $src_y, $width, $height, $width, $height);
	// finally output png image
	//imagepng($final_image, $output_filename.$type, $png_quality);
	imagejpeg($final_image, $output_filename.$type, $jpeg_quality);
	$response = Array(
	    "status" => 'success',
	    "url" => $output_filename.$type
    );
}
print json_encode($response);
```

**Comment by sconsult** [comment]
hi @leocorder 

Glad you worked it out and thank you for making your code available to the community.
Big thank you for that.

Cheers

Mat

**Comment by dpuza** [comment]
sconsult, your code example got corrupted.  the first part didn't get included in the code block style, and so some multiplication "**" on the last line turned into italics

**Comment by dpuza** [comment]
also to clarify for others, it appears that this should replace the first two if statements of the zoom :function in croppic.js starting at around Line 527 in my version

**Comment by drcongo** [comment]
I have an alternate solution which some might find useful, it's certainly what was required in a couple of projects of mine. This allows the user to scale the image down, but only as long as one side meets the bounding box size. So for instance, you can allow users to scale a landscape image down into a square bounding box so that the width matches the bounding box width and the height is smaller. It replaces the same `if` block at the start of the zoom function that @sconsult mentioned...

```
if( newWidth < that.objW && newHeight < that.objH ){

    if( that.imgW > that.imgH ){  // landscape
        newWidth = that.objW;
        newHeight = newWidth/ratio;
        // centre the image vertically
        that.img.css({'top':(that.objH/2) - (newHeight/2), 'left':0});
    }else{  // portrait
        newHeight = that.objH;
        newWidth = newHeight*ratio;
        // centre the image horizontally
        that.img.css({'top':0, 'left':(that.objW/2) - (newWidth/2)});
    }
    
    doPositioning = false;
    
} 
```

I can chuck this in a pull request if you like, but that's really all there is to it.

**Comment by leocorder** [comment]
Great job, @drcongo !
Very useful, indeed!
Thanks

**Comment by fame-media** [comment]
Hi, i know this is old, but i get weird results trying to apply these changes. looks like when cropping a image that is smaller than the canvas, it gets moved to the top somehow...

Using Modal Canvas...

I've tried changing the code from:

```
zoom :function(x){
			var that = this;
			var ratio = that.imgW / that.imgH;
			var newWidth = that.imgW+x;
			var newHeight = newWidth/ratio;
			var doPositioning = true;
			
			if( newWidth < that.objW || newHeight < that.objH){
				
				if( newWidth - that.objW < newHeight - that.objH ){ 
					newWidth = that.objW;
					newHeight = newWidth/ratio;
				}else{
					newHeight = that.objH;
					newWidth = ratio * newHeight;
				}
				
				doPositioning = false;
				
			} 
			
			if(!that.options.scaleToFill && (newWidth > that.imgInitW || newHeight > that.imgInitH)){
				
				if( newWidth - that.imgInitW < newHeight - that.imgInitH ){ 
					newWidth = that.imgInitW;
					newHeight = newWidth/ratio;
				}else{
					newHeight = that.imgInitH;
					newWidth = ratio * newHeight;
				}
				
				doPositioning = false;
				
			}

```
To:
```

zoom :function(x){
			var that = this;
			var ratio = that.imgW / that.imgH;
			var newWidth = that.imgW+x;
			var newHeight = newWidth/ratio;
			var doPositioning = true;
			//default factor 1
			var allowSmallerFactor =1;
			//checking if i am initializing the zoom, there are more elegant possibillities, but for the sake of it.
			if(x !=40)
			allowSmallerFactor=3 //in case of not init, i allow a 3 times smaller picture
			
			if( newWidth * allowSmallerFactor < that.objW || newHeight * allowSmallerFactor < that.objH){
				
				if( newWidth - that.objW < newHeight - that.objH ){ 
                newWidth = that.objW/allowSmallerFactor;
                newHeight = newWidth/ratio;
            }else{
                newHeight = that.objH/allowSmallerFactor;
                newWidth = ratio * newHeight;
            }

            doPositioning = false;

        } 

        if(!that.options.scaleToFill && (newWidth*allowSmallerFactor > that.imgInitW || newHeight*allowSmallerFactor > that.imgInitH)){

            if( newWidth - that.imgInitW < newHeight - that.imgInitH ){ 
                newWidth = that.imgInitW/allowSmallerFactor;
                newHeight = newWidth/ratio;
            }else{
                newHeight = that.imgInitH/allowSmallerFactor;
                newWidth = ratio * newHeight;
            }

            doPositioning = false;

        }

```
OR:
```

		zoom :function(x){
			var that = this;
			var ratio = that.imgW / that.imgH;
			var newWidth = that.imgW+x;
			var newHeight = newWidth/ratio;
			var doPositioning = true;
			//default factor 1
			var allowSmallerFactor =1;
			//checking if i am initializing the zoom, there are more elegant possibillities, but for the sake of it.
			if(x !=40)
			allowSmallerFactor=3 //in case of not init, i allow a 3 times smaller picture.
			
			if( newWidth < that.objW && newHeight < that.objH ){

    			if( that.imgW > that.imgH ){  // landscape
        		newWidth = that.objW;
        		newHeight = newWidth/ratio;
        		// centre the image vertically
        		that.img.css({'top':(that.objH/2) - (newHeight/2), 'left':0});
    			}else{  // portrait
        		newHeight = that.objH;
        		newWidth = newHeight*ratio;
        		// centre the image horizontally
        		that.img.css({'top':0, 'left':(that.objW/2) - (newWidth/2)});
    			}

    		doPositioning = false;

			}  
			
			if(!that.options.scaleToFill && (newWidth > that.imgInitW || newHeight > that.imgInitH)){
				
				if( newWidth - that.imgInitW < newHeight - that.imgInitH ){ 
					newWidth = that.imgInitW;
					newHeight = newWidth/ratio;
				}else{
					newHeight = that.imgInitH;
					newWidth = ratio * newHeight;
				}
				
				doPositioning = false;
				
			}
```

Now i can zoom out - but cropping always gives me this kind of result:

![bildschirmfoto 2017-03-13 um 13 03 39](https://cloud.githubusercontent.com/assets/13729060/23853589/8c3729ee-07ed-11e7-8d6e-d0c07ff59a84.png)

when I actually tried to crop

![bildschirmfoto 2017-03-13 um 13 03 32](https://cloud.githubusercontent.com/assets/13729060/23853617/ad70cdcc-07ed-11e7-9fa7-f12c88096084.png)

Could someone post their complete file changes please?

@leocorder, or @drcongo maybe? Thank you!
 
Cheers

**Comment by hhh062001** [comment]
@leocorder 
Your code is not working fine. I did slightly change in it

if($imgW < $cropW){
				$dst_x = $imgX1;
				if ( $imgH > $cropH ){
					$dst_y = -$imgY1;
				}else{
					$dst_y = $imgY1;
				}
				$src_x = $src_y = 0;
				$width = $imgW;
				$height = $imgH;
			}else{
				$dst_x = $dst_y = 0;
				$src_x = $imgX1;
				//$src_y = $imgY1;
				if ( $imgH < $cropH ){
					$src_y = -$imgY1;
				}else{
					$src_y = $imgY1;
				}
				$width = $cropW;
				$height = $cropH;
			}
			imagecopyresampled($final_image, $cropped_rotated_image, $dst_x, $dst_y, $src_x, $src_y, $width, $height, $width, $height);

**Comment by rudolphreti** [comment]
Hi @sconsult! Thanks a lot for your job.


> I have modified the zoom quickly to allow a factor x to be applied, x is the ratio of how much smaller then your original css defined crop field should be.
> 
> //default factor 1
> var allowSmallerFactor =1;
> //checking if i am initializing the zoom, there are more elegant possibillities, but for the sake of it.
> if(x !=40)
> allowSmallerFactor=3 //in case of not init, i allow a 3 times smaller picture.
> if( newWidth_allowSmallerFactor < that.objW || newHeight_allowSmallerFactor < that.objH){
> 
> ```
>             if( newWidth - that.objW < newHeight - that.objH ){ 
>                 newWidth = that.objW/allowSmallerFactor;
>                 newHeight = newWidth/ratio;
>             }else{
>                 newHeight = that.objH/allowSmallerFactor;
>                 newWidth = ratio * newHeight;
>             }
> 
>             doPositioning = false;
> 
>         } 
> 
>         if(!that.options.scaleToFill && (newWidth*allowSmallerFactor > that.imgInitW || newHeight*allowSmallerFactor > that.imgInitH)){
> 
>             if( newWidth - that.imgInitW < newHeight - that.imgInitH ){ 
>                 newWidth = that.imgInitW/allowSmallerFactor;
>                 newHeight = newWidth/ratio;
>             }else{
>                 newHeight = that.imgInitH/allowSmallerFactor;
>                 newWidth = ratio * newHeight;
>             }
> 
>             doPositioning = false;
> 
>         }
> ```


Console shows: "newWidth_allowSmallerFactor is not defined".

> 
> 
> sconsult, your code example got corrupted. the first part didn't get included in the code block style, and so some multiplication "*" on the last line turned into italics
> 
> I believe that should be:
> 
> ```js
>     if( newWidth * allowSmallerFactor < that.objW || newHeight * allowSmallerFactor < that.objH){
> ```

I corrected it as @dpuza suggested, but it works not good. The image jumps: https://drive.google.com/file/d/1FnmDrAEErBaKzShiQZtSKI_fVoppOZHd/view?usp=sharing

**Comment by rudolphreti** [comment]
@drcongo 

> if( newWidth < that.objW && newHeight < that.objH ){
> 
>     if( that.imgW > that.imgH ){  // landscape
>         newWidth = that.objW;
>         newHeight = newWidth/ratio;
>         // centre the image vertically
>         that.img.css({'top':(that.objH/2) - (newHeight/2), 'left':0});
>     }else{  // portrait
>         newHeight = that.objH;
>         newWidth = newHeight*ratio;
>         // centre the image horizontally
>         that.img.css({'top':0, 'left':(that.objW/2) - (newWidth/2)});
>     }
> 
>     doPositioning = false;
> 
> }

I tested your solution. Zooming and cropping does not work properly.

**Comment by drcongo** [comment]
My solution was 6 years ago @rudolphreti, the library has probably changed a bit since then I'm afraid.
