### ISSUE TITLE
checked a corrupted image

### ISSUE THREAD

**Issue by felipeduardo** [sconsult/croppic#101]
the plugin crashes if the image is corrupted

**Comment by sconsult** [comment]
Hi felipe,

When submitting an issue, please add the image of question, and have a little more detail on the issue.
There are several stages of corruption/degradation. If i try to crop a picture which i you can't even open with program such as Photoshop, it would be unrealistic to believe that an online tool can handle it.

if you can add more info, i would be happy to take a look at it.

Cheers

Mat

**Comment by felipeduardo** [comment]
Hi Mat,

I think the plugin should work the same way as Photoshop, if you try to open a corrupted image plugin must return me an error message, and do not stop working... 

get it?

**Comment by sconsult** [comment]
Hi Felipe,

To be very blunt, i understand what your asking, but you yet again failed to attach an image of question or post any code,logs or anything helpful to help you. 

The image handling is done in the example files in php, however you have the ability to utilize any programming language. Again taking a shot in the dark of what you understand as corrupt image, you can solve it withing the sample files with something along that line:

  $ext = pathinfo($image_file, PATHINFO_EXTENSION);
  if ($ext == 'jpg') {
    $ext = 'jpeg';
  }
  $function = 'imagecreatefrom' . $ext;
  if (function_exists($function) && @$function($image_file) === FALSE) {
       $response = array(
			"status" => 'error',
			"message" => 'bad img file: ' . $image_file,
		);
	}  
        die(json_encode($response));
  }

However as stated in the example files:
/*
*	!!! THIS IS JUST AN EXAMPLE !!!, PLEASE USE ImageMagick or some other quality image processing libraries
*/

If you believe an online open source product should work the same way as a locally installed multi million dollar product, then i have the following suggestion for you.

Make a pull request, implement your solution and i will merge it with the master.

Get it ?

Mat

**Comment by felipeduardo** [comment]
Hi Matt, 

I do not want the plugin make cutting a corrupted image, I want it only on an error return when a User upload an image that this corrupted. When I load a corrupted image plugin is in eternal loading and stop working, but in fact it should return me an error message.

ps: sorry for my poor english... /=

**Comment by sconsult** [comment]
Hi Felipe,

With all due respect, i took my time and outlined a sample solution for you. Did you even read anything what i wrote ?  It describes with sample code what your asking it to do.


Mat
