### ISSUE TITLE
Remove min width restriction rule

### ISSUE THREAD

**Issue by luchorengo** [sconsult/croppic#103]
I'd like to keep zooming out the image despite the container width. Is there a way to remove this restriction rule? I need to create new images with black background if needed.

I took a look into the js code, changed few things but no luck.

Regards.

**Comment by sconsult** [comment]
Hi @luchorengo 

you need to be a little bit more specific, your statement is not clear to me and what has zooming this to do with black background. What are the changes you try to make ?

There is a Zoom Function in croppic, you need to modify your zoom behavior there.
Background needs to be handled in the img_crop_to_file.php, also assuming you are using the examples.

Try to provide an example picture, screenshot, anything what helps to visualize what you want to achieve.

i would love to help and this Link might help you to get achieved what you want (obviously with some modifications)
https://github.com/sconsult/croppic/issues/100

Cheers

Mat

**Comment by sconsult** [comment]
no reply received
