### ISSUE TITLE
Yii2 Advanced Application Support

### ISSUE THREAD

**Issue by nihalcameron** [sconsult/croppic#105]
I'm working with Yii2 Advanced Template. I have added all the js, css and other files to my project. I'm trying to use the MODAL option. This is what I get, and doesn't seem to crop. It just freezes without doing anything (the LoadingBubbles keep jumping).. 

So it doesn't crop or upload. I'm unable to go past that stage. Please Help me out
Here's the code

    
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
              </div>
              <div class="modal-body">
                    <div>
                        <h4 class="centered"> MODAL </h4>
                        <p class="centered">( open in modal window )</p>
                        <div id="cropContainerModal"></div>
                    </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
            </div>
          </div>
        </div>
    

JS in the same file
    <script src=" https://code.jquery.com/jquery-2.1.3.min.js"></script>
   
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.mousewheel.min.js"></script>
    <script src="croppic.min.js"></script>
    <script src="js/main.js"></script>
    <script>
        var croppicHeaderOptions = {
                //uploadUrl:'img_save_to_file.php',
                cropData:{
                    "dummyData":1,
                    "dummyData2":"asdas"
                },
                cropUrl:'<?=Yii::$app->request->baseUrl?>/img_crop_to_file.php',
                //customUploadButtonId:'cropContainerHeaderButton',
                modal:true,
                processInline:true,
                loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',
                onBeforeImgUpload: function(){ console.log('onBeforeImgUpload') },
                onAfterImgUpload: function(){ console.log('onAfterImgUpload') },
                onImgDrag: function(){ console.log('onImgDrag') },
                onImgZoom: function(){ console.log('onImgZoom') },
                onBeforeImgCrop: function(){ console.log('onBeforeImgCrop') },
                onAfterImgCrop:function(){ console.log('onAfterImgCrop') },
                onError:function(errormessage){ console.log('onError:'+errormessage) }
        }   
        //var croppic = new Croppic('cropContainerModal', croppicHeaderOptions);
        //I've tried without commenting the above line then it opens select image window twice and does nothing more
        
        var croppicContainerModalOptions = {
                uploadUrl:'<?=Yii::$app->request->baseUrl?>/img_save_to_file.php',
                cropUrl:'<?=Yii::$app->request->baseUrl?>/img_crop_to_file.php',
                modal:true,
                imgEyecandyOpacity:0.4,
                loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> '
        }
        var cropContainerModal = new Croppic('cropContainerModal', croppicHeaderOptions);

    </script>
I've tried it even without the <?=Yii::$app->request->baseUrl?>. Still there seems to be no luck.

**Comment by nihalcameron** [comment]
This is how it looks before cropping...
![croppic1](https://cloud.githubusercontent.com/assets/10638845/7855360/8a164644-053e-11e5-96b4-97535d42d242.JPG)
After clicking CROP button the bubbles appear and that's it
![croppic2](https://cloud.githubusercontent.com/assets/10638845/7855361/8a23b892-053e-11e5-90cf-9936c29c3003.JPG)

**Comment by pdanzinger** [comment]
I'm not 100% sure if this is the issue, but: In yii2 javascript gets injected right at the end of the page (which makes the page, or at least the html/css part of it, load faster). But this means by the time your script is loaded, jquery isn't.
Note that I assume you use the default asset packs and don't load jquery manually too.

If what I described is the issue, you will want to inject your js and croppic via yii2 too. You could add croppic to your asset pack (see: ) or inject it in the view with $this->registerJsFile().
As for your loading code, you can inject it with $this->registerJs() like that:
![code](https://cloud.githubusercontent.com/assets/11884180/7858488/c6d5416c-0538-11e5-92aa-2f6a5ad74dea.png)

**Comment by pdanzinger** [comment]
Also, it should be noted that this is most likely not an issue with croppic itself.

**Comment by sconsult** [comment]
hi nihalcameron,

Since you have the callbacks added, do you see any output in the browser console? even if croppic appears to freeze, there should be output. Can i ask you to post the output here ?
Do you see any output in the webserver log ?

Without having that its a shot in the dark, but I have seen issues like that with different server configurations and is most of the time related to one of the following:

1.) Filesize of uploaded file is to large for the allowed upload configuration set on your web-server
2.) cropURL --> Assuming you are using the provided php example, it can be an issue with path, or permission. meaning, the path cannot be reached, or you have no permission to write to the folder of your choosing.
3.) Happens way to often, i get emails that one of the php examples doesn't work, and it turns out that the user has made changes, which fail.

What i can tell you for sure is that croppic initiates the crop, but never receives an response, thats why you see the loader bubbles.

Looking forward to your reply.

Mat

**Comment by sconsult** [comment]
no reply received
