### ISSUE TITLE
Changing the name of the key the image is sent 'img'

### ISSUE THREAD

**Issue by newtonianb** [sconsult/croppic#107]
Currently when the image is uploaded it is available in the backend inside the key 'img', how can I change this key to something else?
I tried to look at the source and it seems it's hardcoded there

```
<input type="file" name="img"
```

https://github.com/sconsult/croppic/blob/master/croppic.js#L142

Is that it?

**Comment by sconsult** [comment]
To change the name, yes, don't forget to adjust the php file as well as it asumes the "img" name.

Mat
