### ISSUE TITLE
SCRIPTS: Acces denied on IE10

### ISSUE THREAD

**Issue by franck-roland** [sconsult/croppic#108]
Hi,

Got some trouble when choosing a photo on IE10. I see on my console the message `SCRIPTS: Access is denied`, `croppic.min.js line 6 character 3684`.
I think this is due to the `formData = new FormData(that.form[0]);` line 219 in the not minified source.

**Comment by sconsult** [comment]
Hi @franck-roland 

This appears to be the same issue, which has been addressed here:
https://github.com/sconsult/croppic/issues/33

Let me know if that helped

Cheers

Mat

**Comment by sconsult** [comment]
no response received
