### ISSUE TITLE
How to change PNG Quality

### ISSUE THREAD

**Issue by nishol** [sconsult/croppic#117]
Hi, 

When i save a transparent PNG there is an ugly black line around the picture. Is there a way around this?

Regards
Nishol Chetty

**Comment by sconsult** [comment]
Hi @nishol 

I assume you use the unmodified version of img_crop_to_file.php.  The sample code creates jpeg output, but can easily be modified to reflect your needs.

It would exceed the boundaries of the croppic product if i would start to provide PHP support for the file handling as this is really depending on your implementation and the used libraries. 

However, if you look through the closed tickets you find several approaches how others have solved these issues ;-)

Cheers

Mat
