### ISSUE TITLE
Delete (Remove) Button not working on Firefox

### ISSUE THREAD

**Issue by kitarafrei** [sconsult/croppic#121]
Hello,

I tried the plugin in many browsers and only on my Firefox this behavior is happening, even on the croppic.net website.

Once I upload an image, and click on the X to delete or reset, the loading gif keeps showing with a broken image icon and it doesn't reset, it doesn't show again the upload button. My Firefox version is 32.0.3

I attached and image.

Thanks for checking on it.
![croppic](https://cloud.githubusercontent.com/assets/10803193/8378458/b96c6274-1be7-11e5-96ac-ac16e64a0409.png)

**Comment by sconsult** [comment]
Hi @kitarafrei 

This behavior can have multiple reasons, but most likely you try to upload a picture which is larger then the server permits.

The tool has troubleshoot capabillitlies (callbacks) which are implemented in the croppic site, in the main example (Click here to try it).

Go to the croppic site, hit f12 to open the console in firefox, the load your image. You should see some feedback. The Callbacks are there so you can react in your code to issues, or certain events happening in croppic. Check the documentation for the details.

If my asumption is correct you will get a feedback with the onError Callback.

Any test i just did went successfull with my firefox 37.0.2

Cheers

Mat

**Comment by kitarafrei** [comment]
Hi, thanks for taking the time to respond. Unfortunetely I won't be able to use your plugin :( ... on phones (android and ios) the images are behaving crazy, distortions, rotation without asking to, I cut and the cut is on another direction.... I'm trying to find another solution.... thank you so much for your time

**Comment by sconsult** [comment]
Hi @kitarafrei

Absolutely no problem. My pleasure. In regards to the issues you are describing, we test on android and ipad and can't reproduce your admitingly very broad statements.

If u want us to help you please add printscreens or even better a screencapture vid.

Otherwise good luck with finding another solution

Mat

**Comment by kitarafrei** [comment]
Hi Mat,
I'll try to do it no problem. Also, in any capacity I tried to be disrespectful and I really appreciate what you have done. I wish it was working for me cause it's my favorite of the plugins. 
I'll try to get the print screens from the phones. Thanks

**Comment by sconsult** [comment]
Hi @kitarafrei 

No insult taken, i just pointed out that i can't really do anything about an issue, until i have enough evidence (screenshots) and information about the environment your using.

Appreciate your feedback and  looking forward to your printscreens and info

Mat

**Comment by pampitas** [comment]
Having the same problem with FF. It's in DEMO with PRELOAD. Delete button isn't working.

**Comment by sconsult** [comment]
Hi @pampitas 

I just tested it again with FF 38.0.1 and all examples work fine. As far as i can tell there is no issue.

Can you add the console output here ? Look at my comment from Jun 26, this is the least of the information i need.

I cant really help if i get just a statement that something isn't working without even the minimum of information, especially when i cant replicate it.

Cheers

Mat

**Comment by pampitas** [comment]
Hi Mat,

No info in console, I'm sorry!


*Browser: FF 40.0.3*
When clicking the [X] button in DEMO with PRELOAD, the image preloaded
doesn't disapear and no error is displayed.

That's all I can tell you, unfortunately.

Best regards.



Andrea Schechtmann

*Andrea SCHECHTMANN*
Diseñadora en Comunicación Visual | Desarrollos web
Cel: +54 (9) 221 (15) 548 1634


2015-09-04 8:44 GMT-03:00 Mat Steinlin <notifications@github.com>:
