### ISSUE TITLE
image fails to appear?

### ISSUE THREAD

**Issue by virken** [sconsult/croppic#122]
Hi - I'm using the version of croppic as shown below and pointing it to my <div> with an ID of 'container'

The upload tool appears in the corner, clicking it pulls up the file selector window, I select a file and the uploader disappears - but the image does not appear in the DIV. I tried making the DIV with an alpha of 0 and still no sign of the image. All testing is on localhost. 

I do get an error in the inspector (shown below) and it disappears when I comment out the croppic code below.

Greatly appreciate any troubleshooting help on this.

![image](https://cloud.githubusercontent.com/assets/8900954/8388469/395bc644-1c17-11e5-8adc-3bf0c5bac541.png)

![image](https://cloud.githubusercontent.com/assets/8900954/8388420/dc096c76-1c16-11e5-97db-4472abc0d61e.png)

- - - - - -

cropperHeader = new Croppic('container', croppicHeaderOptions);

var croppicHeaderOptions = {
	//uploadUrl:'img_save_to_file.php',
	cropData:{
	"dummyData":1,
	"dummyData2":"asdas"
	},
	cropUrl:'img_crop_to_file.php',
	customUploadButtonId:'cropContainerHeaderButton',
	modal:false,
	processInline:true,
	loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',
	onBeforeImgUpload: function(){ console.log('onBeforeImgUpload') },
	onAfterImgUpload: function(){ console.log('onAfterImgUpload') },
	onImgDrag: function(){ console.log('onImgDrag') },
	onImgZoom: function(){ console.log('onImgZoom') },
	onBeforeImgCrop: function(){ console.log('onBeforeImgCrop') },
	onAfterImgCrop:function(){ console.log('onAfterImgCrop') },
	onError:function(errormessage){ console.log('onError:'+errormessage) }
};

**Comment by sconsult** [comment]
Hi

Please check:  https://github.com/sconsult/croppic/issues/57

The error you are describing points more likely to a limit in your local Apache/IIS. Please check you max upload limit for your php folder and your permissions are set correctly.

Also you are processing the file inline, rather then on server side, what browser do you use ?

Cheers

Mat

**Comment by sconsult** [comment]
no feedback received
