### ISSUE TITLE
How To set Initial Zoom to 0

### ISSUE THREAD

**Issue by kuluval** [sconsult/croppic#126]
How can I set initial zoom to 0 ... Not found any method for that. Kindly include it.

**Comment by kuluval** [comment]
Found the solution... I have changed the default zoom in croppic source to 0.

**Comment by sconsult** [comment]
Hi @kuluval 

Perfect, you have the option for to set the zoomFactor as an option.
if you are refering to https://github.com/sconsult/croppic/blob/master/croppic.js#L364

i have taken it on the list of items to add.

Cheers

Mat
