### ISSUE TITLE
Image not Cropping correctly. 

### ISSUE THREAD

**Issue by atlantawebco** [sconsult/croppic#127]
The cropping of an image is not working, as you see in this screenshot. The cropImgWrapper div does not give a correct height and sometimes its 0px height for the cropImgWrapper

What's the cause of this?

![crop-issue](https://cloud.githubusercontent.com/assets/6809045/8470459/9cb7cdaa-2059-11e5-918a-d0c2a7666e40.jpg)

**Comment by sconsult** [comment]
Hi @atlantawebco 

A screenshot just shows me the result, without having any idea where you are testing, with what browser, is it a PC or tablet? 

Unfortunately i need a little bit more information then what you have provided.

Looking forward to more information

**Comment by sconsult** [comment]
no further information received
