### ISSUE TITLE
MouseWheel zoom, and touch support? 

### ISSUE THREAD

**Issue by jeacott** [sconsult/croppic#13]
Would really like to see mousewheel zoom, and touch support. currently useless on mobile devices, and mousewheel feels much more natural than button clicks for zooming.

**Comment by sconsult** [comment]
An upgrade for Drag and mousewheel support has been done.
@ijpe Great work, could leverage your work mostly. Have mentioned you also in the upgrade description.

**Comment by ijpe** [comment]
Thank you for the upgrade.
