### ISSUE TITLE
Cannot move picture with croppic.js

### ISSUE THREAD

**Issue by Alplob** [sconsult/croppic#131]
Hello,

I just noticed that it is not possible to move the picture once it has been uploaded when using croppic.js  (no problem in croppic.min.js). Actually two pipes are missing in croppic.js on line 467, just before (e.pageY.

    if (userAgent.match(/iPad/i) || userAgent.match(/iPhone/i) || userAgent.match(/android/i) (e.pageY && e.pageX) == undefined) {

Alplob

**Comment by koceg** [comment]
Fixed it in [PR133](https://github.com/sconsult/croppic/pull/133)

**Comment by sconsult** [comment]
Hi @koceg 

I have merged your fix into the master. Thank you for your help.

Cheers

Mat
