### ISSUE TITLE
Error when cropping an image

### ISSUE THREAD

**Issue by silantevas** [sconsult/croppic#135]
Hello. I have a problem when i testing Croppic on your web-site. For example, I want to crop the image.: https://nws773.files.wordpress.com/2014/03/a1.jpg
When I try to make it in the top frame of the site, I get an error - "image type not supported".
![image01](https://cloud.githubusercontent.com/assets/13259347/8602871/f7b21aa8-269e-11e5-848b-28a70d2227f7.png)
But, when I do it in the examples below, for example in Minimal Controls. I have success! Why?!!!
![image2](https://cloud.githubusercontent.com/assets/13259347/8602881/febd8f44-269e-11e5-9450-bb1bd11fe131.png)

Browser - Firefox v39.0

**Comment by sconsult** [comment]
this might be simple:

The first example uses inline cropping, which is done through the browser, while the others use the php script cropping. Inline (client side) cropping is not supported by all browsers.

Cheers

Mat

**Comment by silantevas** [comment]
Mat, as I understand, the problem is my browser?
1.But, on the page cropppic.net says "croppic is supported on current browsers, such as chrome, firefox, IE 9+, safari and opera". I have Firefox!
2. I tried the same actions on the Chrome browser and get error.
![chrome](https://cloud.githubusercontent.com/assets/13259347/8633494/e3fdfe20-27f5-11e5-85d1-af8efcb5d1c7.png)

ps: I don't understand how the first example does not use a php-script?

**Comment by sconsult** [comment]
Hi @silantevas 

1.) Yes it does, but that doesn't mean in any configuration mode. If you check the source, the first example uses ProcessInline Option, this is not supported on all browsers. Keep in mind croppic.net is a summary of samples how you can run croppic.

![image](https://cloud.githubusercontent.com/assets/10435334/8649961/f481f466-293c-11e5-827b-8563692144a8.png)

2.) if you look into the closed tickets there are 7 tickets resolved with similar issues:
https://github.com/sconsult/croppic/issues?q=is%3Aissue+Unexpected+is%3Aclosed

Simple solution for you, when you run it local on your servers and you want to have backwards compatibillity, your first example should look like this

![image](https://cloud.githubusercontent.com/assets/10435334/8650094/392ca312-293e-11e5-999f-07f50d805a64.png)


Cheers

Mat
