### ISSUE TITLE
Why no onSuccess callback?

### ISSUE THREAD

**Issue by StevenFlecha** [sconsult/croppic#136]
Why is there no onSuccess callback?

onAfterImgCrop is still called even when OnError is also called.. so there is no proper onSuccess callback which makes it impossible to properly initiate other action after cropping etc is done automatically

**Comment by sconsult** [comment]
Simple anwser, because nobody requested it so far ;-)
if you are not seeing an error, it is fairly reasonable to assume that the crop is successful.

if you look through the pending open items approved for development, the callbacks will be updated.

Cheers

Mat
