### ISSUE TITLE
Activate Upload on an Event and Custom Button for Crop/Save

### ISSUE THREAD

**Issue by kriskd** [sconsult/croppic#139]
Is there a way I could implement the following two enhancements:

1.  I do the uploading and cropping in a Twitter Bootstrap modal.  The user clicks a link on my page, the TWBS modal opens with croppic in it.  Instead of having the user then click on the green upload button or even a custom upload link, is there a way I can have trigger the upload immediately when the modal opens?  I tried the `click` event and` trigger('click')` on a custom upload link in the modal and that did not work.

2.  Similar to `customUploadButtonId`, is there a way to have a custom crop/save button.  I would like to remove the crop/save icon from the image space and have a button off the image to do the save.  I'm concerned my users will not associate that button with saving the image and lose their changes.

**Comment by marcosschroh** [comment]
I have already implemented the point 2. If you can I can upload this feature

**Comment by kriskd** [comment]
@marcosschroh Yes, I would appreciate you sharing with me, pointing me to a PR or similar so I can implement this.

**Comment by kriskd** [comment]
I ended up taking a stab at this myself.  @marcosschroh Is this similar to what you did?  It seems to work:

https://github.com/kriskd/croppic/commit/7d746c2e9e8d0abed393c47111c696912684d117

**Comment by marcosschroh** [comment]
Hey.. sorry for the late response... Take a look in my repo: https://github.com/marcosschroh/croppic/blob/master/croppic.js
I have added the extra option when you initialize the plugin, it is customCropButtonId. You have to pass the id of the selector, It's all.

**Comment by kriskd** [comment]
I have submitted PR #143 to create the custom crop button as well as an option to not display the red reset button.
