### ISSUE TITLE
Resize/Crop with Imagick

### ISSUE THREAD

**Issue by wordsongoku** [sconsult/croppic#14]
Hi,

first of all thank you for this great script. I'm trying to save the cropped and resized file to my server. I'm using Imagick for this. For some reason it seems not to work properly tough. I'm using: 

$cropImage->cropImage($cropW, $cropH, $imgX1, $imgY1);

It resizes the image to the given width and height, but for X and Y it seems to always use 0, as I can move the image around where I want but it always gives me the same image area as output.

What am I doing wrong?

Thank you

**Comment by mystycs** [comment]
Possible to share the code for this?
