### ISSUE TITLE
Upload hangs in IE9

### ISSUE THREAD

**Issue by ataravati** [sconsult/croppic#140]
When I try to upload a picture in IE9, the upload hangs, and I get an HTTP 408 error in Fiddler.

Here's the request header:

POST /xxx/Photo/Upload HTTP/1.1
Accept: image/gif, image/jpeg, image/pjpeg, application/x-ms-application, application/vnd.ms-xpsdocument, application/xaml+xml, application/x-ms-xbap, application/x-shockwave-flash, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*
Referer: http://xxx
Accept-Language: en-ca
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/5.0; SLCC1; .NET CLR 2.0.50727; .NET CLR 3.5.21022; .NET CLR 3.5.30729; .NET CLR 3.0.30729; InfoPath.2; MS-RTC LM 8; .NET4.0C; .NET4.0E)
Content-Type: multipart/form-data; boundary=---------------------------7dfab2a9d016a
Accept-Encoding: gzip, deflate
Host: xxx
Content-Length: 287862
Proxy-Connection: Keep-Alive
Pragma: no-cache
Cookie: _ga=GA1.2.843648415.1388681041; ASP.NET_SessionId=lv4vltjfj4fg4mnzr54oowa2; __RequestVerificationToken_L2RiYXBwcy9BcG9UZWw1=-sNjCur2n_c8kIePkQo3X6BChkezTeWWREF4lVrvM6BuyeM0sIV_q0Irldfn-ykx5ARhKQkRuzxPh2PeQOLR0wUl6uiaUDygcA2P4YHXDGo1

And, here's the response:

HTTP/1.1 408 Request body incomplete
Date: Thu, 16 Jul 2015 15:47:42 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Cache-Control: no-cache, must-revalidate
Timestamp: 11:47:42.186

The request body did not contain the specified number of bytes. Got 0, expected 287862

**Comment by sconsult** [comment]
Hi @ataravati 

How do you initialize croppic can you share this info here as well ? are you using processInline:true ? this is only available after IE10.

Cheers

Mat

**Comment by ataravati** [comment]
Hi Mat,

I figured what the problem was. I'm using cropping in an asp.net MVC
application. The widget is on a partial view that gets refreshed via an
Ajax call after the image is uploaded, cropped, or deleted. Apparently,
that somehow screws the iFrame. I don't know exactly what happens, but it
works if I refresh the whole page after each upload, crop, and delete.

Thanks,
Ali
