### ISSUE TITLE
Change the Background color in a Rotated Image

### ISSUE THREAD

**Issue by anigrama** [sconsult/croppic#144]
Hello, Thanks for the great plugin!

How i can change the background color in a (Scaled and Rotated) image?
By default is black and i want to be white.

**Comment by ReSsCZE** [comment]
I had this problem too.

Just add this lines:
  $whiteBackground = imagecolorallocate($rotated_image, 255, 255, 255); 
  imagefill($rotated_image,0,0,$whiteBackground); // fill the background with white  

after:
 
// crop rotated image to fit into original rezized rectangle
$cropped_rotated_image = imagecreatetruecolor($imgW, $imgH);

**Comment by sconsult** [comment]
Hi @anigrama and @ReSsCZE 

Thank you for sharing the issue, and specifically a possible solutions. 

Cheers

Mat
