### ISSUE TITLE
Auto Crop how many pictures

### ISSUE THREAD

**Issue by zhoujiqiu** [sconsult/croppic#146]
I have more than one image to be cropped, cut at initialization, how to get all the pictures of the size and coordinates. I want to do automated cutting effect of all the pictures.
![123](https://cloud.githubusercontent.com/assets/13549280/8949832/233b25b0-35eb-11e5-8311-d332f7209c32.png)

**Comment by sconsult** [comment]
You could achieve this by re-initializing crop-pic after every crop, you can add the callback function onAfterImgCrop  Within your code for onAfterImgCrop, reinitialize croppic with the next picture in line..

Mat
