### ISSUE TITLE
300 dpi images

### ISSUE THREAD

**Issue by skar95** [sconsult/croppic#148]
I think croppic is not able to crop 300 dpi images.

**Comment by skar95** [comment]
There are just some 300 dpi images that are not working properly, I don't know what's the problem!

**Comment by skar95** [comment]
Uncaught SyntaxError: Unexpected token <

**Comment by sconsult** [comment]
Hi @skar95 

The problem you are describing might be also related to max file upload size. check your php.ini to what you have set upload limit. Check for the following:
upload_max_filesize = xxM
post_max_size = xxM
and make sure you have the correct permissions to the folder.

Mat

**Comment by sconsult** [comment]
no response received
