### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aviemet** [sconsult/croppic#149]
Hopefully this doesn't seem like a nit-picky request, but I'm trying to debug an issue I'm experiencing by inspecting the main js file and it would really help if the code itself had some descriptive comments. 

My specific issue is that once I choose an image and it uploads, it will only appear with the cropping interface if `processInline` is set to `true`. This particular flag isn't mentioned on your main site, so I was hoping for insight by inspecting the code. If there were at least a sentence or two in comments describing some of the less intuitive blocks, that would be very helpful.

Thanks

**Comment by sconsult** [comment]
Hi @aviemet 

My apologies that this feature has not been documented properly. I have now more time and will updated the site as well as the code with the latest pull requests pretty soon.
To give you a preview :
processInline handles the file upload within your browser, rather then using the the server (img_save_to_file.php).
processInline is not available on all browsers especially IE requires 10+.

If you need to debug, register callbacks, then open a console to see the output

if you check the example on croppic.net, this is how you register the callbacks and put the output to the console.

onBeforeImgUpload: function(){ console.log('onBeforeImgUpload') },
onAfterImgUpload: function(){ console.log('onAfterImgUpload') },
onImgDrag: function(){ console.log('onImgDrag') },
onImgZoom: function(){ console.log('onImgZoom') },
onBeforeImgCrop: function(){ console.log('onBeforeImgCrop') },
onAfterImgCrop:function(){ console.log('onAfterImgCrop') },
onError:function(errormessage){ console.log('onError:'+errormessage) }

Hope that helps

Mat

PS. most problems with processInline false, are either related to
1.) apache/ php is configured to not allow the size of file you want to upload
2.) Permission issues

**Comment by sconsult** [comment]
hi @aviemet 

Todays update also addresses the documentation of processInline, Please reopen a ticket if you have still an issue.

Cheers

Mat
