### ISSUE TITLE
Croppic upload image not working in Safari Browser

### ISSUE THREAD

**Issue by srinu11ch** [sconsult/croppic#153]
Hi,
I'm using croppic from www.croppic.net upload button not working there is no response,
directly open your site url http://croppic.net/ in safari and try to upload image from "CLICK HERE TO TRY IT" but no response,
Browser: Safari,
Version:5.0

**Comment by kriskd** [comment]
I have run into a similar issue testing with browserstack.  The upload button does not open the file browser.  This is testing using Snow Leopard and Safari 5.1.  It also does not work on the demo site.  http://www.croppic.net/  Can this be supported?

**Comment by sconsult** [comment]
@srinu11ch and @kriskd 

Todays update has addressed this issue, please test croppic.net again and download the latest version

Mat

**Comment by lanetteambhavin** [comment]
Hi..
I have already form tag in master page. Now I have implement croppic in content page. This is not working, Can you please help me.

**Comment by sconsult** [comment]
Hi @lanetteambhavin 

Please create a new Issue, rather then adding your question to a closed Issue.

Based on your statement i have no idea how i should help you. Your 
To explain it differently: You drove your car to a car repair shop and dropped it off with the comment "it's not working". However you failed to describe even the smallest basics of what is "wrong"  (the radio, the engine, doesn't turn on, the wiperblades etc.) 

Having that said, please open a new Issue, provide code examples (how you initialize croppic), upload printscreens of WHAT is not working or document it clearly, provide some feedback about your troubleshooting and your environment.

That's how we(the community) can help you.

Cheers

Mat

**Comment by lanetteambhavin** [comment]
Hi @sconsult 
Thank you for quick replay.
I have solved this bug and update on my code. I apologies for that.

Thank you
Cheers 
Vishal

**Comment by srinu11ch** [comment]
HI @sconsult 
Thanks for Replay,
Issue still Raised when i am click the upload button opend the file browser, but image not display  console error displaying as : processInline is not supported by your browser , please find 
the  attached screen shot
![croppic_safari](https://cloud.githubusercontent.com/assets/3338406/9402577/757634a0-47fc-11e5-8949-fd3252bdfb50.png)

**Comment by sconsult** [comment]
Hi @srinu11ch 

This is not the placve for a new Issue, please open a new issue if needed.
You will find your anwser in the documentation: The error indicates that your browser doesnt support the processInline flag.

Mat
