### ISSUE TITLE
Set initial zoom as variable

### ISSUE THREAD

**Issue by EricDu** [sconsult/croppic#158]
When I upload an image to Croppic, it's always a little bigger than the container. After looking through the parameters, I couldn't find a way to "fix" it so that it would fill the container exactly. After looking at the code, I found **that.zoom(40);** in the initialScaleImg function. Changing the value to **that.zoom(0);** solved my problem.

I suggest adding initialZoom as an option, defaulting to a value of 40 for backwards compatibility, but that can be overwritten on initialization like zoomFactor. In my case, adding **initialZoom:0** to the parameters.

**Comment by sciolini** [comment]
+1

**Comment by sconsult** [comment]
This will be merged today into master. Thank you @EricDu
