### ISSUE TITLE
Multiple upload/crop on one page.

### ISSUE THREAD

**Issue by chetanmadaan** [sconsult/croppic#162]
Hi -

I am trying to do multiple upload/crop one one page but as soon as I change cropContainerModal var to something else... It stops working... even on a single instance.

Is that a known issue?

**Comment by svilius** [comment]
Hi,

did you change both var?

![modal](https://cloud.githubusercontent.com/assets/14276218/9987551/8a2a5a94-6051-11e5-9e85-a296526f3788.png)

**Comment by chetanmadaan** [comment]
Ofcourse i did... Would you like me to upload the code to jsfiddle or something?

**Comment by svilius** [comment]
I`m not sure what you trying to do, in one container you want to u/c more than one img?

**Comment by sconsult** [comment]
Hi @chetanmadaan 

In order to help you you need to provide your implementation code. Without that its guesswork at best. I can be something simple as a typo, but again without providing the minimal information we can't help.

Cheers

Mat

**Comment by chetanmadaan** [comment]
I gave up on it for now... but i will try to put up a fiddle or something.
