### ISSUE TITLE
Cropped image - blur

### ISSUE THREAD

**Issue by svilius** [sconsult/croppic#163]
Hi,

I have downloaded whole website, everyting is working, but after "crop", image looks very blurry. I tested same image on croppic.net, everything look great, where is the problem? 

Thank you for answer.

Quality = 100
![bna](https://cloud.githubusercontent.com/assets/14276218/9952768/5eae23ee-5de2-11e5-9ea1-f4171e6fdf07.jpg)

Update:
![wrong](https://cloud.githubusercontent.com/assets/14276218/9990879/9ee7e0a2-606d-11e5-9b51-9e82947b4d4a.jpg)

**Comment by svilius** [comment]
The problem is with server, but still didint find it...

**Comment by sconsult** [comment]
Hi @svilius 

I see the results. Can you provide more information about your enviroment ? Also do you see the same issues on your server and on croppic.net or just your server ?

Cheers

Mat

**Comment by svilius** [comment]
Hi @sconsult 

on croppic.net server everything is fine.

This is on my server (Im using host1plus provider):
http://www.threemki.com/crop/

Php extensions
![image](https://cloud.githubusercontent.com/assets/14276218/10220337/5b816542-684f-11e5-9f2a-cced8a1c1247.png)

**Comment by sconsult** [comment]
Hi @svilius

Unfortunately your link is not available. I have to assume everything around how you implemented croppic, as you are not sharing invocation code or crop implementation (aka are you using img_crop_to_file.php or your own implementation to crop the file).

My assumption is at this point that you use the img_crop_to_file.php and with that said there are several possible reasons why re-sizing/cropping could produce a blurry image, however mosty they are environment specific.

Here a couple references to what might be the issue:

http://stackoverflow.com/questions/8017372/this-picture-become-blurry-after-resizing
http://stackoverflow.com/questions/15248461/php-file-upload-script-produces-blurry-image

Hope that gets you started.

Mat

**Comment by svilius** [comment]
Hi @sconsult 

after I download croppic.zip I dont change any files or something like that, just copy/paste. 

I tried on xampp, same story. I think it`s a problem with image processing libraries

**Comment by sconsult** [comment]
no further updates received

**Comment by Askancy** [comment]
I too have this problem. someone has already solved the mystery?

**Comment by ogunm** [comment]
this is rotating problem, change your backend scripts if you not rotate pictures you cant use rotate functions.

if you change img_crop_to_file.php 79. line

`imagecopyresampled($final_image, $cropped_rotated_image, 0, 0, $imgX1, $imgY1, $cropW, $cropH, $cropW, $cropH);`

to

`imagecopyresampled($final_image, $resizedImage, 0, 0, $imgX1, $imgY1, $cropW, $cropH, $cropW, $cropH);`

you cant rotate images but blurry problem solved.
