### ISSUE TITLE
change imageMagick to graphicsMagick,it is uncorrect

### ISSUE THREAD

**Issue by 466023746** [sconsult/croppic#165]
gm(path + arr[arr.length - 1])
                //.resize(fields.imgW, fields.imgH)
                .rotate('black', fields.rotation)
                .crop(fields.cropW * scale, fields.cropH * scale, fields.imgX1 * scale, fields.imgY1 * scale)
                .write(path + time + '.png', function (err) {
                    if (!err) {
                        return res.send(200, {"status": "success", "url": '/static/images/upload/' + time + '.png'})
                    } else {
                        console.log('gm-resize-err', err);
                        return res.send(500, {"status": "error", "message": err});

                    }
                });
use imageMagick is OK,
but use graphicsMagick is NotOk
original pic
![1443162221518](https://cloud.githubusercontent.com/assets/10148735/10094930/302cb95c-6398-11e5-8061-582ec5e2124e.png)
use imageMagick
![1443162344072](https://cloud.githubusercontent.com/assets/10148735/10094934/3737bb02-6398-11e5-89c8-76d541abc2ef.png)
use graphicsMagick
![1443162946191](https://cloud.githubusercontent.com/assets/10148735/10094938/3c070408-6398-11e5-993b-2fed7b243e55.png)

**Comment by sconsult** [comment]
hi @466023746 

Thank you for your outline,  i see the results you are producing, but don't know what you want to show with the code segment.

if you have a working implementation of graphicsMagick i would encourage you to share it with the community.

Cheers

Mat
