### ISSUE TITLE
zooming with mousewheel too fast causes bugs

### ISSUE THREAD

**Issue by sangyoo91** [sconsult/croppic#167]
zooming with mousewheel too fast causes bugs

Just like the title states, zooming with mousewheel too fast causes croppic to break.

Is there a solution coming up for this?

**Comment by sangyoo91** [comment]
To be more elaborate on the issue, the image will fly off outside the crop area to the direction of where the cursor is in relative to the center of the crop area.

**Comment by sconsult** [comment]
Hi @sangyoo91 

I am was not aware of such a described issue. I guess it also depends on how you have set up your mousewheel.

if you want to change the default behavior, respectively the zoom factor

**Comment by sangyoo91** [comment]
I'll try and get back with you :) Thank you!

**Comment by sangyoo91** [comment]
I have tried playing around with the line above but have not been successful...

**Comment by sconsult** [comment]
Anybody else has this issue ? Can't fix what i cant reproduce.

Mat

**Comment by sconsult** [comment]
nothing more received on this matter
