### ISSUE TITLE
Not working for pre-loaded image

### ISSUE THREAD

**Issue by rezoanulalamriad** [sconsult/croppic#172]
Hi Support,

The image cropper doesn't work properly when there is a pre-loaded image.
Please advise.

Cheers,
Riad.

**Comment by sconsult** [comment]
Hi @git-parentify-co 

Please add a little more information. How do you expect anybody to help you if you are not providing minimal information, such as enviroment your testing, browser, implementation code, etc.

You basically telling me, its broken but nothing else.

If you add more information, i'm sure the community will help you

Mat

**Comment by git-parentify-co** [comment]
Hi Mat,

Thanks for your reply.
Basically we are using linux hosting platform for deployment and windows for local run.
croppic is good but only problem is when we have a image already loaded. Then the delete button doesn't work. The picture just stays. We have the expectation to have it like, when an image already there then we can delete that image and upload a new image and crop.
Do you understand now ?

Cheers,
Riad.

**Comment by sconsult** [comment]
Hi @git-parentify-co 

I understand what the issue might be, but yet again, your using words and i cant see your implementation. Your not giving me any facts.
If you cant provide minimal log output, such as browser console, when you implement the callbacks, apache error log, information about, if the issue happened only on your system or also on croppic.net. etc. i really don't know how you expect anyone to help you.

To use an analogy:  Its like me coming to you and telling you the my car has an issue, without giving any further information, and i expect you to fix it for me. You simply cant without knowing more about the issue.

As more information you can provide as better, but without most community members dont even bother to look at your Issue ;-)

Cheers

Mat

**Comment by aleangelico** [comment]
Hello, I have the same issue. 

The code is the Preload example at http://www.croppic.net/

how can you upload a new picture in the Preload example?

for example, a user can upload a profile picture. Later, he wants to change it, but I want to show him/her his older profile picture and give him/her the opportunity to change it

How can I achive this?

**Comment by rezoanulalamriad** [comment]
Exactly that's what I was trying to make the creator understand ...

Cheers,
Riad
  
_______
  
Parentify
Rezoanul Alam Riad - VP of Engineering
833 Broadway, 2nd Floor
New York, NY 10003

Cell: +88 017-3483-7654
www.parentify.co

https://www.linkedin.com/pub/rezoanul-alam/72/5b0/494

**Comment by sconsult** [comment]
Hi @aleangelico 

Thank you for your question. Preload was ment for administrators who have the pictures already available, and don't want the user to select it.

Natively what your trying to achieve is not implemented. however you can implement a workaround.

Instanciate croppic with cropper options for a preload.
Add a callback, on reset.  (within this function re-instanciate the existing croppic as a new regular upload croppic)

This would give you
- User goes to your site, sees his profile picture. he clicks on the x to change it, you will reload croppic which blanks his picuture and hi will see the upload button and can proceed from there.

@rezoanulalamriad re-read your tickets, your saying "its not working properly". You have also not replied to my latest reply to you. Way to go to get free support, buddy.

I need to repeat myself. if you want help state exactly what are you trying to achieve. @aleangelico asked a very specific question, while @rezoanulalamriad just stated it is not working properly. Big difference.

Mat

**Comment by rezoanulalamriad** [comment]
Got it. Thanks for calling me buddy.
It's a lot for me, since you are the plugin creator.
You mean a lot to me.

Also, thanks for the workaround answer to him. I'll do that also. thumbs up.

Cheers,
Riad
  
_______
  
Parentify
Rezoanul Alam Riad - VP of Engineering
833 Broadway, 2nd Floor
New York, NY 10003

Cell: +88 017-3483-7654
www.parentify.co

https://www.linkedin.com/pub/rezoanul-alam/72/5b0/494

**Comment by aleangelico** [comment]
@sconsult  Thanks a lot mate. 

BTW, your plugin is awsome!
;)

**Comment by rezoanulalamriad** [comment]
Centainly!

**Comment by Cactusx09** [comment]
function Refresh(){
        $('#wrap').load('create.php #wrap', function () {
            var croppicContainerPreloadOptions = {
                uploadUrl: 'img_save_to_file.php',
                cropUrl: 'img_crop_to_file.php',
                outputUrlId: 'cropOutput',
                enableMousescroll: true,
                loaderHtml: '<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> '
            }
            var cropContainerPreload = new Croppic('cropContainerPreload', croppicContainerPreloadOptions);
        });   
    };
$(document).ready(function () {  
    var croppicContainerPreloadOptions = {
        uploadUrl: 'img_save_to_file.php',
        cropUrl: 'img_crop_to_file.php',
        loadPicture: 'images/sl-1.jpg',
        outputUrlId: 'cropOutput',
        enableMousescroll: true,
        loaderHtml: '<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',
        onReset: function () {
            Refresh();
        }
    }
    var cropContainerPreload = new Croppic('cropContainerPreload', croppicContainerPreloadOptions);
});

**Comment by rezoanulalamriad** [comment]
Hi Mat,

Picture is distorted in Mac Safari. Any clue ?

Riad

**Comment by sconsult** [comment]
Hi Riad

Please open a new Issue Ticket for a new Issue. Additionaly please add more information, such as a screenshot what you are seeing, Browser version you are using etc.

Mat
