### ISSUE TITLE
Zoom image errors

### ISSUE THREAD

**Issue by mrpeo** [sconsult/croppic#173]
Croppic error zoom, image scale left and smaller than crop frame. See screenshot for more detail.

Thanks.
![croppiczoom](https://cloud.githubusercontent.com/assets/4709861/10389941/6de9e294-6e9f-11e5-9870-22fefa9659ae.jpg)

**Comment by portugaonline** [comment]
Try this in css:

img {
	max-width: none !important;
}

**Comment by mrpeo** [comment]
Thanks you, this solved my problem.
