### ISSUE TITLE
Auto redirect after crop

### ISSUE THREAD

**Issue by DSheed** [sconsult/croppic#174]
Hello, 

Firstly I would like to say that this is an amazing little solution. There needs to be a donate button somewhere !!!

Ok, I have managed to add croppic to my site and all is working perfectly, the only problem I have is that users sometimes do not select the crop icon to save the cropped image. I have a button on the page that redirects them back to the site and they just click on it expecting the button to crop and save the image before redirecting them. So my question is this,  I would like to remove the button I have, forcing them to use the crop icon. Is there any way I can add a "redirect" to another page when the crop icon is clicked? I am using the minimal controls set up. I basically downloaded the whole website and just removed the elements I didn't need so it is the same code, just embedded in my website.

I am only a beginner but I would have thought I just need a simple line of code somewhere that redirects to another page once the crop button is clicked and the picture is saved

Thanks in advance

**Comment by sconsult** [comment]
Hi Dsheed,

That can be very simply achieved.  Croppic allows you to add callbacks, and i assume what you are looking for is the onAfterImgCrop Callback. This is invoked when the crop has been finished.

Here an untested example:

var cropperOptions = {
			onAfterImgCrop:	function(){ window.location.replace('http://my-new-location.com');
}
}

Let me know if thats what your looking for

Mat

**Comment by DSheed** [comment]
Thank you for replying. This really is an amazing add in for my website.

Thanks for all your hard work guys, it is very much appreciated
