### ISSUE TITLE
Crop Problem

### ISSUE THREAD

**Issue by portugaonline** [sconsult/croppic#175]
When i crop the image i have this error:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by svilius** [comment]
did you edit some files?

**Comment by sconsult** [comment]
Hi @portugaonline

**Comment by sconsult** [comment]
No feedback received from  @portugaonline 

Closing ticket

**Comment by kavin-90** [comment]
I got same error and found i was not sending Json data.
