### ISSUE TITLE
large image files not cropping even with php.ini set up

### ISSUE THREAD

**Issue by danimal1076** [sconsult/croppic#176]
Even with my confirmed php.ini settings with all three parameters suggested on your homepage set to 32+mb, I still cannot crop any image file that is over 800k.  Can upload large images fine with a simple upload script. I am using the img_crop example php processing file. Any ideas would be appreciated, thank you. The same thing happens on your example page with images around 800k and am doubting that your ini settings are lower than 800k, or even 1 mb. thanks

**Comment by sconsult** [comment]
Hi @danimal1076 

Couple items:

You saying that you have set it to 32+ but not what your set to that. There is also no log or info attached to the ticket, so i can only take your word for it.

Lets start here:

Can i ask you for the folloing:
Output of  phpinfo();
Apache Error Log (just the segment where you upload the File)
Browser Console output:  I hope and assume you have callbacks implemented to get feedback from croppic.

Looking foward to your info

Mat

**Comment by sconsult** [comment]
no further information received.

**Comment by aelan-id** [comment]
If we use PHP in NTS mode, we must add "FcgidMaxRequestLen 2097134" (it means 2 mb, adjust to the needs) to the file "httpd-fcgid.conf".

Hope this is a solution.
