### ISSUE TITLE
Please add accept="image/png, image/jpeg"

### ISSUE THREAD

**Issue by akmil** [sconsult/croppic#177]
Please add ability of setting upload image type. For example I wold like to set available types like this:  

` that.type = "image/png, image/jpeg" `     
 
      <input type="file" accept=that.type name="img" id="' + that.id + '_imgUploadField">

**Comment by sconsult** [comment]
Hi @akmil 

If you look through the tickets this has been multiple times discussed. Due to the incompatibillity with IE8/9 we decided not to add this to the master. However you can easely add this in your implementation as you have outlined.

Mat
