### ISSUE TITLE
Sending a csrf token field

### ISSUE THREAD

**Issue by kickthemooon** [sconsult/croppic#180]
how would a send something like this with the post request:
```
<input type="hidden" name="_token" value="{{ csrf_token() }}"/>
```

**Comment by sconsult** [comment]
Hi @kickthemooon 

User @gilsondev has implemented a option in croppic, you can find his implementation here:

https://github.com/sconsult/croppic/pull/11

Hope that helps

Mat

**Comment by carbontwelve** [comment]
@kickthemooon use `uploadData` and `cropData` settings like so:

```javascript
var cropperOptions = {
     uploadData: {
          '_token': 'your token'
     },
     cropData: {
          '_token': 'your token'
     }
};

var cropper = new Croppic('containerId', cropperOptions);

```

**Comment by sconsult** [comment]
its assumed that both solution solved the @kickthemooon 's question
