### ISSUE TITLE
Load picture from php generated image

### ISSUE THREAD

**Issue by rokasmi** [sconsult/croppic#183]
Hello,
first, thanks for a great tool! :) 
My problem is that, im trying to load a picture from php generated image file.
Option:
`loadPicture:'mainImage.php?id='+rid,`
Everything looks fine and image loads. 
But after pressing the green crop button it hangs and not save.
Wheres the problem and how can i solve it?

**Comment by sconsult** [comment]
Hi @rokasmi 

The problem can be related to several items, but without any further information from you im not able to help you.

What i need from you is the following:

1.) to add all callbacks to the cropper option:

This gives you feedback on what might be going wrong. The output will be shown in the browser console. Please copy this output in your ticket.

onBeforeImgUpload: function(){ console.log('onBeforeImgUpload') },
				onAfterImgUpload: function(){ console.log('onAfterImgUpload') },
				onImgDrag: function(){ console.log('onImgDrag') },
				onImgZoom: function(){ console.log('onImgZoom') },
				onBeforeImgCrop: function(){ console.log('onBeforeImgCrop') },
				onAfterImgCrop:function(){ console.log('onAfterImgCrop') },
				onReset:function(){ console.log('onReset') },
				onError:function(errormessage){ console.log('onError:'+errormessage) }

2.) check your system settings, maxupload etc. (you find all parameters in closed tickets). It might be that your serve cannot handle the filesized.

3.) Also make sure you have the proper permissions to the folder you are trying to access.

Let me know

Cheers

Mat

**Comment by sconsult** [comment]
no further information received
