### ISSUE TITLE
405 method not allowed error

### ISSUE THREAD

**Issue by Jake-lav** [sconsult/croppic#185]
Hello, first off, this is a really neat tool, and the documentation on the website is great for new to the field guys like me, but i am running into a problem. 

I have the front-end croppic features mostly working, however I am getting a 405 method not allowed error for the ajax POST request. From what my research has told me,  need to add CORS support on everything. But as i said I am new to this, so my question is, does croppic have CORS support in its ajax request?

Thanks

**Comment by sconsult** [comment]
Hi @Jake-lav 

I was just made aware of an issue in the img_crop_to_file.php file. Around line 40 please remove the following line:    error_log("jpg");

You can see it here
https://github.com/sconsult/croppic/blob/master/img_crop_to_file.php#L40

Let me know if this solved the issue

Mat

**Comment by Jake-lav** [comment]
That did not solve the issue because the issue was not with your tool but how i was using my routes. but thanks for your response!
