### ISSUE TITLE
cropic IE 10 `response.status` undeifned error on `onAfterImgCrop` callback

### ISSUE THREAD

**Issue by jangidgirish** [sconsult/croppic#186]
Hi,

I am getting `response.status` undeifned error in IE 10 browser, when i click on `crop` icon then error occurs please see image
![untitled](https://cloud.githubusercontent.com/assets/4018017/11293003/69f0f432-8f7b-11e5-8793-7287ca48e2ea.png)

**Comment by sconsult** [comment]
Hi @jangidgirish 

I see you are running it locally or on a testserver, do you have the same feedback on croppic.net ?
Can you provide the exact version /release of your IE10 ?

Thank you

Mat

**Comment by jangidgirish** [comment]
issue resolved now, thank you,
