### ISSUE TITLE
add tags for each version

### ISSUE THREAD

**Issue by maruilian11** [sconsult/croppic#193]
would you please consider adding tags for each version so that we can add your lib on https://cdnjs.com/ with **git auto-update**.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6520

**Comment by sconsult** [comment]
Hi @maruilian11 

I have barely time to maintain the site properly and we have several request for additional taging or integration such as node.js.

If you can find somebody who is willing to maintain it i would be happy to work with this person, otherwise i would have to say no.

Mat

**Comment by maruilian11** [comment]
thanks for your reply, seems there is only one version, we'll add it first without git auto-update config.

**Comment by PeterDaveHello** [comment]
@sconsult I can help tag the versions.
