### ISSUE TITLE
can we save as cropped original big image then container width/height version ??

### ISSUE THREAD

**Issue by wipau** [sconsult/croppic#20]
hi i liked ur plugin. and im using on my social website i modified a little ur script and working awesome..

users can select image and they uploading image croping original image but i want save a big version original cropped image..

how can i do this or (this plugin now sending imgx1 and imgy1 for container size) i want original image size too...

i could tell what i want..
Regards...

**Comment by Novocaine88** [comment]
You can modify the php crop script like so;

here are some post vars;
```
// original sizes
$img_init_w = $_POST['imgInitW'];
$img_init_h = $_POST['imgInitH'];
```

Then in the section above the resizing/saving etc;

```
// lets make a copy of the original first
// ================================================================
$original_img = imagecreatetruecolor($img_init_w, $img_init_h);
imagecopyresampled($original_img, $source_image, 0, 0, 0, 0, $img_init_w, $img_init_h, $img_init_w, $img_init_h);
imagejpeg($original_img, $original_filename.$type, 100);
```

Note: the variable names are probably different to those in the example code provided for this. The same logic can be applied if you want multiple sizes of the images other than the cropped version too.

**Comment by sconsult** [comment]
+1 for @Novocaine88 for his anwser

**Comment by junuNGT** [comment]
Hi, I think what he meant was he wanted to save the cropped image in a bigger size than the size of the croppicheadercontainer.
Eg: continersize:300x300

**Comment by Novocaine88** [comment]
That's what my post is doing. It's saving the original image size. I'm on my phone right now so can't post example code, but you could apply the same as above and just change the resolution to what you want.

**Comment by junuNGT** [comment]
@Novocaine88 im not able to get it to work, please post a sample code if possible.
