### ISSUE TITLE
afterUpload - be triggered twice

### ISSUE THREAD

**Issue by bpystep** [sconsult/croppic#213]
If i have callback onAfterImgUpload, my function triggered twice. Why?
**Croppic.prototype.afterUpload**
1. `img.load(function(){
...
                    if (that.options.onAfterImgUpload) that.options.onAfterImgUpload.call(that);
                });`
2. `if (that.options.onAfterImgUpload) that.options.onAfterImgUpload.call(that);`

Maybe one trigger remove?

**Comment by sconsult** [comment]
Hi @bpystep 

This is the correct behavior, one upload is for the processInline (aka Filereader API) the other through formdata Upload. A third for loading an existing image.

I hope that helps ;-)

Mat

**Comment by bpystep** [comment]
Hi, @sconsult

Why correct? I has one callback and i want one trigger! But "croppic" launch twice, its not good. I can write my code later, maybe you want.

**Comment by sconsult** [comment]
Hi  @bpystep 

If you add the callback listener, it is only invoked once. you can test this on the croppic.net page.
I would need to see how you are initializing croppic and how your utilizing it.

As outlined above the implementation is for 3 different cases which each is only invoked once depending on the implementation.

![image](https://cloud.githubusercontent.com/assets/10435334/14052098/01630f5a-f29e-11e5-9d94-af7df2030584.png)

**Comment by bpystep** [comment]
@sconsult

I write my code later, but i not near PC, but you can view on http://crop.bpystep.ru

*I modified twice trigger

**Comment by sconsult** [comment]
Hi @bpystep 

I am not sure if your understanding what im telling you for the 3rd time now. the triggers are ok. i would need to see your implementation. Writing code to fix something which you just think is wrong is not the right approach.

Post her the code how you invoke croppic and i will certainly have a look

Mat
