### ISSUE TITLE
Image is not saving to server through php code, any help ?

### ISSUE THREAD

**Issue by dshack1** [sconsult/croppic#218]

**Comment by Dmitri10** [comment]
Hi. there are two files-examples: img_save_to_file.php(saves to server image after upload image) and img_crop_to_file.php(saves cropped version).
in js-object croppic you have to set urls for these scripts. 
Too much reasons may be(not installed GD library, wrong path/rights to upload folder/scripts, wrong definition of js object... ) - you should check all these moments or show some code and error description/log etc.. or nobody can answer...

Besides you may clone source to local machine and test it as is - it has to work

**Comment by kavin-90** [comment]
Works superb i'm using it in my php project.

**Comment by dshack1** [comment]
IT does work perfectly fine. Just had to do some readjustments to the file to save properly.

**Comment by kavin-90** [comment]
Do u need my code? Its in php framework
