### ISSUE TITLE
Big image cover the full page

### ISSUE THREAD

**Issue by hhh062001** [sconsult/croppic#226]
Big image cover the full page when Uploading

![cropic](https://cloud.githubusercontent.com/assets/2488370/16123118/4571492c-3403-11e6-9ab8-0ab30717b9cb.jpg)

**Comment by kriskd** [comment]
Are you returning the image height and width after upload?

`After successful image saving, you must return the following json. 
( image width and height required for limiting max zoom, so images dont come out blurry. )`

```
        `{
            "status":"success",
            "url":"path/img.jpg",
            "width":originalImgWidth,
            "height":originalImgHeight
        }
            `
```

**Comment by hhh062001** [comment]
Can we crop the image on the click of form "Save" button?
