### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by DK986** [sconsult/croppic#234]
![croppic-dontwork](https://cloud.githubusercontent.com/assets/20738774/17269699/dc56b3c2-564f-11e6-9c56-173ea79bf736.png)
Why does the croppic-plugin dont work?
I cant figure it out.

Please help.

**Comment by sconsult** [comment]
In order to help you you have to be a little bit more specific "what" doesn't work. It doesn't load, it give you an error ? 

Based on that simple screenshot, i dont see you defining any "cropperOptions" and use yourID

Here an example(which you can see on the website):

var croppicContainerEyecandyOptions = {
                uploadUrl:'img_save_to_file.php',
                cropUrl:'img_crop_to_file.php',
                imgEyecandy:false,  
                loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',
                onBeforeImgUpload: function(){ console.log('onBeforeImgUpload') },
                onAfterImgUpload: function(){ console.log('onAfterImgUpload') },
                onImgDrag: function(){ console.log('onImgDrag') },
                onImgZoom: function(){ console.log('onImgZoom') },
                onBeforeImgCrop: function(){ console.log('onBeforeImgCrop') },
                onAfterImgCrop:function(){ console.log('onAfterImgCrop') },
                onReset:function(){ console.log('onReset') },
                onError:function(errormessage){ console.log('onError:'+errormessage) }
        }

```
    var cropContainerEyecandy = new Croppic('cropContainerEyecandy', croppicContainerEyecandyOptions);
```
