### ISSUE TITLE
Cropped image becoming blur

### ISSUE THREAD

**Issue by hhh062001** [sconsult/croppic#236]
It is working fine on PHP version 5.3 and 5.4. But when i am using croppic on 5.6 then it is creating problem. After image crop the new image becoming blur. 

Orignal Image
![orignal-image](https://cloud.githubusercontent.com/assets/2488370/18060740/42f4da7c-6e39-11e6-9181-e55af67a372e.jpg)

Cropped Image
![crop-image](https://cloud.githubusercontent.com/assets/2488370/18060753/4c8f8348-6e39-11e6-867e-3c8e339ab866.jpeg)

**Comment by ZdenekPNJ** [comment]
HI,
I´ve the same problem with PHP version 5.5.12. I´ve $jpeg_quality = 100. I´dont know, where is the problem.
Original
![15](https://cloud.githubusercontent.com/assets/18365590/18098211/8c0a5158-6ee1-11e6-8d2d-0a185b58ba92.jpg)
Cropped
![test_11602](https://cloud.githubusercontent.com/assets/18365590/18098222/9b43daae-6ee1-11e6-9f20-cff726177e2d.jpg)

**Comment by hhh062001** [comment]
I have solved the issue.

Add
imageconvolution($original_img,array(array(-1,-1,-1),array(-1,16,-1),array(-1,-1,-1)),8,0);
After imagecopyresample and before imagejpeg()
Imageconvolution is used to sharpen the image
