### ISSUE TITLE
Cropping on mobile with responsive Foundation Zurb template

### ISSUE THREAD

**Issue by ZdenekPNJ** [sconsult/croppic#239]
Hi,
I´m trying to aplicate this on the Zurb Foundation template, which is responsive. But when I try to crop on mobile, the CropOutput window is too large.

Do you know, how to make it for mobile phone?
Thanks

**Comment by sconsult** [comment]
this would need to be implemented with Exit-If.
Currently not supported, but the community is encouraged to implement it
