### ISSUE TITLE
want to add flip horizontal and vertical option next to zoom.

### ISSUE THREAD

**Issue by Pravin2587** [sconsult/croppic#29]
Hi guys, Great Plugin, i am trying to add flip(not rotate) event next to zoom button but can't figure how to get, is there any way to be done. let me know how to do that, as am not good in jquery. and also is it possible to edit from same position once cropped, to edit again or zoom cropped image....???

Thanks

**Comment by sconsult** [comment]
With the latest updates on croppic, you can add a rotatefactor of 180 to the cropperoptions. This would achieve what your looking for.
