### ISSUE TITLE
On IE 10, getting SCRIPT5: Access is denied

### ISSUE THREAD

**Issue by colddiver** [sconsult/croppic#33]
This happens on the http://www.croppic.net/ demo page.

To reproduce:
1. Go to http://www.croppic.net/ and open up the Console in IE
2. Click the "click here to try it" button
3. Select image and click open
4. Notice the error...

**Comment by pawanataress** [comment]
Hi colddiver,

Can you please help me to work this in IE 9/10

**Comment by sconsult** [comment]
i could not replicate the problem in my IE10 with rollups. is this still an issue ?

**Comment by sconsult** [comment]
No response received, if it still occurs, please reopen a new Issue

**Comment by shenyangcn** [comment]
Hi I use few lines to fix this issue.
Just add below line in isAjaxUploadSupported will solve the issue.
		isAjaxUploadSupported: function () {
		    var isIE10 = false;
		    /*@cc_on
		        if (/^10/.test(@_jscript_version)) {
		            isIE10 = true;
		        }
		    @*/
		    if(isIE10){
		    	console.log("User is using IE 10.");
		    	return false;
		    }
            var input = document.createElement("input");

**Comment by shenyangcn** [comment]
Hi I use below way to overcome this issue.
Just detect the browser version...

		isAjaxUploadSupported: function () {
		    var isIE10 = false;
		    /*@cc_on
		        if (/^10/.test(@_jscript_version)) {
		            isIE10 = true;
		        }
		    @*/
		    if(isIE10){
		    	return false;
		    }

**Comment by ahm-3d** [comment]
i have updated the latest croppic version. ie9 and ie11 works great, however ie10 still errors with "SCRIPT5: access is denied"

@sconsult , where do i need to add the code which you have suggested to get ie10 to work

**Comment by shymkovayu** [comment]
Hello,

I'm also having this issue in IE10. I tried every solution from this topic. I don't get the acces error, but the omage doesn't upload also.

**Comment by sconsult** [comment]
Hi @shenyangcn @ahm-3d 

Thank you for the input, Can you give me the Exact IE10 version you are using? i cant replicate the Issue.

Thank you

Mat

@shymkovayu 
Your problem most likely has nothing to do with this issue. If you want to have support, you need to post at least enviroment you are using, browser console output or error message your receiving.
if you use IE10 and you are using the first example on croppic, you problem is that processInline is not supported, the solution is simple..don't use processInline ;-) 
You would have seen this when you open your browser console ;-)

**Comment by shenyangcn** [comment]
Hi @sconsult ,

Please find IE version from below screen shot,
But I think it is much related to the image itself, not all the image have this issue, only those images cross domain will encounter this.

You may try with http://i.imgur.com/3tU4Vig.jpg for test. A higher IE version which downgrade to IE 10(with developer tool)also will not get the result.
I get the image from below link,
http://stackoverflow.com/questions/24087757/three-js-and-loading-a-cross-domain-image

I think this is a IE 10 issue,
But to make it work either by upload the image  with base64 encoded, or by iframe should be good.
<img width="505" alt="screen shot 2015-08-28 at 12 04 11 pm" src="https://cloud.githubusercontent.com/assets/909825/9538951/fb9622cc-4d7c-11e5-893a-c6f8c9eb2e67.png">

**Comment by sconsult** [comment]
hi @shenyangcn 

Can you please repost the console output, i can only see half of it. Are you using the latest version ?

Mat

**Comment by shenyangcn** [comment]
Hi @sconsult ,

I'm using the latest code from github,
And I also tried from croppic website. 
Below image is captured from another PC with IE 10.


![20150829222841](https://cloud.githubusercontent.com/assets/909825/9562372/7d885fb8-4e9d-11e5-9af9-80542f1221d0.jpg)

**Comment by shymkovayu** [comment]
Hi @sconsult ,

I guess I described the situation a little bit incorrect :) 

I get the SCRIPT5: Access denied croppic.js line 220 character 6.
IE version 10.0.9200.16521

I meant that when I'm trying solutions from this topic the access error from console disappears, but the image still doesn't upload. 

I also tried to set processInline to false, nothing changed.

**Comment by sconsult** [comment]
Hi all.

I was finally able to replicate the issue on the IE10. The problem has been resolved with the update from today.
Please reopen a new ticket if another IE10 issue persists.

Cheers

Mat

**Comment by KarthikRocker** [comment]
http://answers.microsoft.com/en-us/ie/forum/ie10-windows_7/ie10-script5-access-is-denied/e87bdb30-7f2a-4510-bfa3-a22b995f777b?auth=1

**Comment by sconsult** [comment]
Hi @KarthikRocker 

Not sure what your comment should outline. The Problem your referring with your link has been addressed.  If you are experiencing an issue, please open a new ticket.

Mat
