### ISSUE TITLE
Support for rotation

### ISSUE THREAD

**Issue by nyxem1** [sconsult/croppic#34]
Isn't it would be good, if  you add support for rotation. I tried to add rotation, then cropping but it would work only for 180 deg rotation. For 90 deg rotation its giving Out of Memory exception. Obviously, the width of the bounding boxes are larger in that case.
Any chances that I can implement this or you should be upgrading it.

**Comment by sconsult** [comment]
Rotation will be implemented in the next release. Should be only a few days away

**Comment by sconsult** [comment]
Rotation has been implemented and is part of the update. Check out croppic.net for a working example.

Mat

**Comment by nyxem1** [comment]
oh great...... thanks for such an update... really great effort.

**Comment by nyxem1** [comment]
i have implemented a .net version of croppic. How can I send you ?
