### ISSUE TITLE
Support filter file type (only image) in dialog choice image

### ISSUE THREAD

**Issue by daniel82hien** [sconsult/croppic#36]
Hi,

If croppic support filter file type (only image) in dialog choioce image, please show me how to set option.

Thanks.

**Comment by sconsult** [comment]
@daniel82hien the verification for the fileupload is currently done throught the php implementation of the fileupload.
in img_save_to_file, you will find the following code. This prevents wrongly uploads
$allowedExts = array("gif", "jpeg", "jpg", "png", "GIF", "JPEG", "JPG", "PNG");

You can edit the codebase from croppic.js direcly, In the current codebase search for

// CREATE UPLOAD IMG FORM
its around line 136.

Add the accept attribute to the input type file, to set the filter.

<input type="file" accept="image/*" />

Keep in mind accept is not supported in older browsers. (IE8, IE9)

Here the link to w3schools.
http://www.w3schools.com/tags/att_input_accept.asp


Hope this helps
