### ISSUE TITLE
Parsing error of a json response

### ISSUE THREAD

**Issue by gerardnll** [sconsult/croppic#4]
The plugin throws the following error when it receives a Content-Type: application/json as a response once the image is uploaded:
> Uncaught SyntaxError: Unexpected token o

I think that the plugin is parsing an already parsed json object. When the content type is changed to text/html this error doesn't happen. 
The correct Header if we are returning a json object is "application/json" so i think this should be fixed appropriately.

Thanks guys for the good work.

**Comment by sconsult** [comment]
this has been fixed, additionally a  new callback has been implemented, onError, which provides feedback and allows you to react to an error within your app.
