### ISSUE TITLE
image doesn't show up in box

### ISSUE THREAD

**Issue by bogal** [sconsult/croppic#45]
When i select an image, it doesn't show up in the box? I get the cropping tool bar at the top of the container, and the json result from img_save_to_file.php is all ok, but there is no image?

**Comment by sconsult** [comment]
we have added a Callback onError, which provides you feedback about the Issues you are experiencing.
from what you are describing it is most likely either related to folder permission or the file which you are trying to upload exceeds the file upload limit set in the configuration of your php.ini
