### ISSUE TITLE
Zoom logic error with certain kind images

### ISSUE THREAD

**Issue by greenlaw110** [sconsult/croppic#47]
when I upload [this image](http://ge.tt/2ce0ig22/v/0) to croppic I always get error, even croppic on the official site couldn't handle that image correct
![capture](https://cloud.githubusercontent.com/assets/216930/4782062/7465cb80-5cd8-11e4-8cbc-11d5bd11d429.PNG)

**Comment by sconsult** [comment]
the limitations set currently on croppic is that the image dimensions cannot be smaller then the croppic window which you have defined. 
If you would go below that, the cropped picture would show black boarders. What would be your expected result ?

**Comment by sconsult** [comment]
closed could not reproduce on latest version, and no reply received.
