### ISSUE TITLE
Leveraging HTML5 for uploadless cropping

### ISSUE THREAD

**Issue by Bastes** [sconsult/croppic#5]
Using this technique:
http://www.html5rocks.com/en/tutorials/file/dndfiles/

The cropping could be prepared before the file is uploaded so the image can be processed as soon as it is received by the server, and the user doesn't have to wait for the upload to be complete to start cropping.

wdyt ?

**Comment by sconsult** [comment]
@ptheofan The inlineprocessing /clientsite processing will be part of the next release, we will add some verification's but you will be mentioned as the source for the implementation.
Stay tuned ;-)
Mat

**Comment by sconsult** [comment]
this has been implemented
