### ISSUE TITLE
Delete uploaded Images

### ISSUE THREAD

**Issue by derSteffen** [sconsult/croppic#51]
Hello!

I'm looking for a solution that the upload original images are delete from the server after the croppiing and after clicking the cancel-button.

Thank you very much!

Greetings

Steffen

**Comment by sconsult** [comment]
Hi Steffen,

Not knowing why you want to delete it right away, i would guess that you don't need the original anymore, and you want to save disk space. if this assumption is correct then you have essentially 3 options:

1.) modify the codebase for croppic,
2.)  make a pull request and add the feature you need.
3.) solve the problem with a script and cronjob( if your linux user).

1, is not to suggest as it doesnt keep you upgrade compatible with new features.
   However you could add the delete in the crop:function(){ after a succesfull if(response.status=='success'){
2.) is only recommended if you feel comfortable enough to implement it by yourself
3.) this is probably how i would solve the issue. (i will not delete ever picture right away)

Cheers

**Comment by Alplob** [comment]
You can delete the uploaded image simply by adding the following line in *img_crop_to_file.php*, just above the line 	*imagejpeg($final_image, $output_filename.$type, $jpeg_quality);*
```unlink ($imgUrl); ```

**Comment by sconsult** [comment]
+1
