### ISSUE TITLE
Display image wihtout click on download button

### ISSUE THREAD

**Issue by skunkies** [sconsult/croppic#52]
Hi, Is there a possibility to set a default image without clicking on download button.

**Comment by sconsult** [comment]
Hi skunkies,

Yes there is, check out the new croppic.net. We just released another major update, and the preload function is now part of the code.

Have fun with it

Mat

**Comment by skunkies** [comment]
Hi thanks for your answer. Is there a possibility to force the zoom - to
shrink the image more?
Thanks

Le vendredi 23 janvier 2015, Mat Steinlin <notifications@github.com> a
écrit :
