### ISSUE TITLE
Accessing Reponse Data

### ISSUE THREAD

**Issue by JordanDalton** [sconsult/croppic#53]
What is the proper way to go about access JSON response data when using, for example, onAfterImgUpload()?

I saw on #17 that it was stated that the 2nd argument being passed into the function, onAfterImgUpload:function(arg1, arg2) would allow for accessing response data but it does not.

For now I'm having to use window.response but I wanted to confirm if there is a better way to go about this. Thank you for your help.

**Comment by sconsult** [comment]
Hi JordanDalton,

I just released today an update with a new CallBack Function called:  onError.
It actually handles response Data exactly in the way you need it and i believe it can be a good guideline for you on how to optimize your code.


Just as a little Hint:
on index.html (register the callback and create a function with code):  
line 557: onError:function(errormessage){ console.log('onError:'+errormessage) }

in croppic.js (checking if there is a reason to call the registered callback, if yes call it)
line 560:  if (that.options.onError) that.options.onError.call(that,response.message);

Let me know if you have any questions.

Cheers

Mat

**Comment by gnumoksha** [comment]
I think that this feature it is necessary

**Comment by sconsult** [comment]
hi @gnumoksha 

I'm not sure what you are implying. the feature is already implemented. if you need something else or found a bug, please open a new ticket.

Cheers

Mat

**Comment by gnumoksha** [comment]
@sconsult the feature that @JordanDalton say about: a way to get response data returned by onAfterImgUpload. Considerer that the user needs to get values in the response, currently he needs to make like bellow, right?

```
onAfterImgUpload: function(var1, var2) {                                         
        if (typeof(window.response.id) != 'undefined') {                         
            console.log(window.response.id);                             
        } else {                                                                 
            console.error(window.response);      
       }
}
```
