### ISSUE TITLE
cropData with dynamic value

### ISSUE THREAD

**Issue by Alplob** [sconsult/croppic#54]
Hello,

I am using this excellent plug-in but I meet a problem: I would like to rename the cropped file with a dynamic value (i.e. the id of the selected item in my page). I tried to use the cropData function with a given field but it seems it does not take into account if it has been updated, with Ajax per example. The value is always the same that had been set up during loading of the page. I have tried to use the method *cropperHeader.reset();* but I do not see any improvemement.

Is it possible to set up cropData like this?
` cropData:{ 'picture_name': $('input#sp_id').val() } `

Thanks!

**Comment by Alplob** [comment]
Hello, I re-open that issue because actually my work around is not that good. The behaviour of the plug-in is much better when it is not destroyed/created each time I display an item on my page through a ajax call.

**Comment by sconsult** [comment]
hi Alplob,

Can you post some sample code , how you you run croppic and where do you think it doesnt refresh i will certainly take a look.

Mat

**Comment by Alplob** [comment]
Hello Sconsult, 

Thanks a lot for your reply. My page is made of 2 sections. The left pane includes a list of items and selecting one display it in the the right pane thanks to an ajax call. Below is the code I use. You can see in the function *refresh_content* that I do not use the method *refresh* but I modify the option, I destroy and re-initialize Croppic.

```javascript
// Function called each time an item is displayed in the right pane
function refresh_content(id) {
	$.post('./ajax/_item_display.php', { line: id }, function(json) { 
		$('#item_id').val(json.item_id);
		$('#item_code').val(json.item_code);
		$('#item_name').val(json.item_name);
		....
		cropperOptions.imgUrlInit = './files/index.php?type=item&picture_id=' + $('#item_id').val();
		cropperOptions.cropData = { 'type_picture': 'item', 'picture_name': $('#item_id').val() };
		cropperHeader.destroy(); 
		cropperHeader = new Croppic('item_picture',cropperOptions);
	}, 'json');
};

// Initialization
var cropperOptions = {
	uploadUrl:'./files/img_save_to_file.php',
	cropUrl:'./files/img_crop_to_file.php',
	uploadData:{ 'type_picture': 'item' },
	cropData:{ 'type_picture': 'item', 'picture_name': $('item_id').val() },
	imgUrlInit: './files/index.php?type=item&picture_id=' + $('item_id').val(), 
	onError: function(errormsg){ console.log('onError:'+errormsg); notification_action_forbidden(errormsg); },
	doubleZoomControls:false,
	zoomFactor:50,
	rotateFactor:90,
	rotateControls:true,
	modal:true
}
var cropperHeader = new Croppic('item_picture',cropperOptions);
```

**Comment by lucascaprio** [comment]
You can do a mask in the button crop and change the object values, like this:
```javascript
$('.some-button').on('click', function () {
   cropperOptions.cropData.picture_name = $('input#sp_id').val();
   $('.cropControlCrop').click();
});
```

**Comment by sconsult** [comment]
Hi @Alplob

Did the solutions from @lucascaprio help you solve the issue ? If yes please close the Issue, otherwise update the issue with your latest response.

Thanks @lucascaprio for being an active part of the open source community

Mat

**Comment by Alplob** [comment]
Not really. Actually I am using Croppic to maintain a facebook of items, which means two actions: 
1. show the picture of the displayed item (the function *refresh_content(id)* in my code, with the help of #22 )
2. update that picture if the user thinks it is necessary (the normal Croppic usage)

The solution of @lucascaprio works well for the point 2. but not for the point 1. The ideal situation would be that the .reset() method reloads all the options value with their 'instant' value and not keeping those defined when the page got loaded.

**Comment by sconsult** [comment]
Hi @Alplob 

Ok let us make a step back. Your original question was that the value, even if changed does not reflect when the same croppic instance is used. The value stays the same.
You are using the following (which is correct)

cropData:{ 'picture_name': $('input#sp_id').val() }

In your refresh function, your reinstatement croppic.

// Function called each time an item is displayed in the right pane
function refresh_content(id) {
    $.post('./ajax/_item_display.php', { line: id }, function(json) { 
        $('#item_id').val(json.item_id);
        $('#item_code').val(json.item_code);
        $('#item_name').val(json.item_name);
        ....
        cropperOptions.imgUrlInit = './files/index.php?type=item&picture_id=' + $('#item_id').val();
        cropperOptions.cropData = { 'type_picture': 'item', 'picture_name': $('#item_id').val() };
        cropperHeader.destroy(); 
        cropperHeader = new Croppic('item_picture',cropperOptions);
    }, 'json');
};

if i understand you correctly this code is what you want to achieve (replace this in your index for the preload):

 var croppicContainerPreloadOptions = {
				uploadUrl:'img_save_to_file.php',
				cropUrl:'img_crop_to_file.php',
				cropData:{ 'type_picture': 'item', 'picture_name': 'test mat'},
        		        loadPicture:'assets/img/night.jpg',
				enableMousescroll:true,
				onAfterImgCrop:function(){
				for (var key in cropContainerPreload.options.cropData) {
					if(cropContainerPreload.options.cropData.hasOwnProperty(key) &&  key == "picture_name") {
							alert("before change key: "+key+" value: "+cropContainerPreload.options.cropData[key]);
							cropContainerPreload.options.cropData[key] ="new value";
							alert("after change key: "+key+" value: "+cropContainerPreload.options.cropData[key]);							
							
							//formData.append( key , that.options.cropData[key] );
					}
				}
				cropContainerPreload.options.cropData  },
				loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> '
		}
		cropContainerPreload = new Croppic('cropContainerPreload', croppicContainerPreloadOptions);


I utilize there the onAfterImgCrop:function.

When initializing the croppic, the original picture name is "test mat", when the first crop is done, i change the value for the existing croppic instance to "new value". Output example attached.

I believe you could take it from here, to modify the code to your liking without destroying and reinitalizing a new crop.

All without destroying the old and re instantiating a new croppic.
![step 1](https://cloud.githubusercontent.com/assets/10435334/7657978/63779d6a-fb04-11e4-8c55-68ae5eda5bc6.jpg)
![step 2](https://cloud.githubusercontent.com/assets/10435334/7657980/637d4e86-fb04-11e4-8477-4d1459035ef2.jpg)
![step 3](https://cloud.githubusercontent.com/assets/10435334/7657979/637b785e-fb04-11e4-97e8-129a785ea89a.jpg)

**Comment by Alplob** [comment]
Thanks a lot for your answer, I got your point, that is fine!

**Comment by AristideSalvatore** [comment]
You can pass a variable adding:

On the upload image
uploadData:{ 'id': $('#id').val() },

if you want on the crop image
cropData:{ 'id': $('#id').val() },

Insert a input to make the POST variable
<input type="text" id="id" name="id" value="<? echo $variable; ?>" />

and add on the file img_crop_to_file or img_save_to_file

$value= $_POST["id"];
$output_filename = "images/$value";
