### ISSUE TITLE
problem with simple implementation

### ISSUE THREAD

**Issue by AmaroDelCapo** [sconsult/croppic#57]
I recive this error:

Uncaught SyntaxError: Unexpected token <

I have replicated the example in http://www.croppic.net/

Thank you for you appreciated support,
best regards
Amaro

**Comment by sconsult** [comment]
thank you for sharing both, the problem and your solution

**Comment by sconsult** [comment]
In the update from today, error handling has been implemented and the sample scripts updated with checks for write permissions
