### ISSUE TITLE
Unlimited Zoom

### ISSUE THREAD

**Issue by richprich** [sconsult/croppic#59]
Hi,

How can i edit the script to make it unlimited zoom? I found the zoom function( zoom :function(x){ ) on the croppic.js but i have no idea how to edit. 

Many thanks...

**Comment by sconsult** [comment]
Hi richprich, with unlimited zoom also increases the blur factor. what is it you are trying to achieve ?

**Comment by richprich** [comment]
Hi Sconsult,

I'm creating an user gallery for my website. When i crop the picture, i need to focus on the face. But some small dimension picture cannot be crop due to maximum zoom. Can you teach me where should i edit the zoom function in the script?

Thanks

**Comment by sconsult** [comment]
Hi richprich,

Can you provide me a link with an test image, i will take a look if it is a problem which we should address in the master,

Cheers

Mat
