### ISSUE TITLE
Zoom out - Wrong positioning resulting in added black bars

### ISSUE THREAD

**Issue by JanGessinger** [sconsult/croppic#6]
Issue: When you zoom out a picture, sometimes the image does not adjust to the max size of the crop box

Result: The cropped Image has black bars at the sides/borders

Solution:
Some changes in the zoom() method:
zoom :function(x){
			var that = this;
			var ratio = that.imgW / that.imgH;
			var newWidth = that.imgW+x;
			var newHeight = newWidth/ratio;
			var doPositioning = true;
			var doPositioningClearTop = false;
			var doPositioningClearLeft = false;
			
			if (newWidth < that.objW || newHeight < that.objH) {
			    if (newWidth - that.objW < newHeight - that.objH) {
					newWidth = that.objW;
					newHeight = newWidth / ratio;
					doPositioningClearLeft = true;
			    } else {
					newHeight = that.objH;
					newWidth = ratio * newHeight;
					doPositioning = false;
			    }
			} 
			
			if( newWidth > that.imgInitW || newHeight > that.imgInitH){
				if( newWidth - that.imgInitW < newHeight - that.imgInitH ){ 
					newWidth = that.imgInitW;
					newHeight = newWidth / ratio;
					doPositioningClearTop = true;
				}else{
					newHeight = that.imgInitH;
					newWidth = ratio * newHeight;
					doPositioning = false;
				}
			}
			
			that.imgW = newWidth;
			that.img.width(newWidth); 
			
			that.imgH = newHeight;
			that.img.height(newHeight); 
	
			var newTop = parseInt( that.img.css('top') ) - x/2;
			var newLeft = parseInt( that.img.css('left') ) - x/2;
			
			if (newTop > 0) { newTop = 0; }
			if (newLeft > 0) { newLeft = 0; }
			
			var maxTop = -(newHeight - that.objH); if (newTop < maxTop) { newTop = maxTop; }
			var maxLeft = -(newWidth - that.objW); if (newLeft < maxLeft) { newLeft = maxLeft; }
			
			if (doPositioning) {
			    that.img.css({ 'top': doPositioningClearTop ? 0 : newTop, 'left': doPositioningClearLeft ? 0 : newLeft });
			}

		    if(that.options.imgEyecandy){
				that.imgEyecandy.width(newWidth);
				that.imgEyecandy.height(newHeight);
				if (doPositioning) {
				    that.imgEyecandy.css({ 'top': doPositioningClearTop ? 0 : newTop, 'left': doPositioningClearLeft ? 0 : newLeft });
				}
			}	
			
			if (that.options.onImgZoom) that.options.onImgZoom.call(that);

		},

Now, when you zoom the picture, it will always be in the range of the crop box. There will never be added black bars.

I had to write this fix because I am using this script in combination with a C# MVC project. Whenever I sent a picture to the controller that was not completly in the range of the crop box, I got an error at the C# method "Clone":
var bmpImage = new Bitmap();
var cropArea = new Rectangle(imgX1, imgY1, cropW, cropH);
bmpImage.Clone(cropArea, bmpImage.PixelFormat); <-- error

**Comment by sconsult** [comment]
could not replicate the issue, please open a new issue if the problem persists.

Mat
