### ISSUE TITLE
Cropping large images

### ISSUE THREAD

**Issue by katmaha** [sconsult/croppic#60]
As far as I can tell the only way to control the size of the crop area is via css.
My issue is what if I want to crop very large images, e.g. 1400px wide (for banners etc).
That's a pretty large container and not very user friendly. Anyway around this?
Thanks!

**Comment by sconsult** [comment]
Will look into this issue, if you could provide a link with an example picture you try to crop it would help our test team.
Mat

**Comment by mathfrick** [comment]
I need help too!   is it possible to create a small div with the same ratio as the large file avec crop it ...

**Comment by sconsult** [comment]
An untested solution could be as follwed

you can set the attributes for the crop container also as followed:

 $('#cropContainerModal').css({"width":"{_________}px",
								"height":"{_________}px",
								"border":"1px solid #ccc",
								"position":"absolute",
								"top":"0",
								"bottom":"0",
								"left":"0",
								"right":"0",
								"margin":"auto"});
  
});

so what you could do is to implement within croppic, after the file is loaded, you get the dimensions width and height from the image, then scale it down to your desired size, and set the css new with the code sample above.

you find the following code in croppic for the height and width.

that.imgInitW = that.imgW = response.width;
that.imgInitH = that.imgH = response.height;

**Comment by musaddiq-pk** [comment]
I m having problem to crop large image on my site. 
Here is my web url https://www.furniturenation.com/croppic/.
The image I've tried to upload is attached below.

![abc](https://cloud.githubusercontent.com/assets/11736070/6918261/a9fd7c08-d7c5-11e4-9395-5d801ab25f87.jpg)

**Comment by sconsult** [comment]
i just checked your site, looks ok to me. Is there still an issue.
![test](https://cloud.githubusercontent.com/assets/10435334/7505915/6949f04c-f426-11e4-9f89-ffd23cfab184.jpg)

**Comment by sconsult** [comment]
no feedback received. closing issue.
