### ISSUE TITLE
Javascript error when I try to upload image

### ISSUE THREAD

**Issue by R9NALD9** [sconsult/croppic#61]
Thanks for this awesome library!

I'm trying to implement into wordpress and the page loads fine.

As soon as I select an image, and click on open I get the following errors:

POST http://thehoneymoonfund.co.za/wordpress/wp-content/themes/honeyTheme/img_save_to_file.php - 500 Internal Server Error	1,55s	
jquery1..._min.js (line 4)
"NetworkError: 500 Internal Server Error - http://thehoneymoonfund.co.za/wordpress/wp-content/themes/honeyTheme/img_save_to_file.php"
img_sav...ile.php
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
...ction(b){if(a.JSON&&a.JSON.parse)return a.JSON.parse(b+"");var c,d=null,e=m.trim...

In essence I get a 500 internal Server Error on the img_save_to_file.php file and a JSON unexpected character error on my Jquery1.11.1 file.

Please help, I urgently need to get this working.

**Comment by sconsult** [comment]
Unexpected Character in that section normally implies that either:
 1.) your trying to upload a picture which is larger then what you have defined in php.ini as max post size.
2.) You have a permission issue and you cant write to the folder where you want to save the file

**Comment by sconsult** [comment]
Latest Update from today should provide you feedback on the issue, when utilizing the Callback Method onError
Cheers
Mat
