### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <     (index):1

### ISSUE THREAD

**Issue by kwp** [sconsult/croppic#62]
There was already an issue with this topic. The solution was a changing of the folder rights.
But my temp folder ist on 755 and i dont know wich other folder should have other right-restrictions.
I tried other restrictions - same error.
Is there an other solution? 
I installed the complete dl-folder on my server.

By the way there is an issue on your documentation page:
"var cropperHeader = new Crop..." should be "var cropperHeader = new Croppic..."

**Comment by sconsult** [comment]
Hi kwp,
Just released an upgrade to croppic with some fixes (the one you just mentioned).
The problem you are describing might be also related to max file upload size. check your php.in to what you have set upload limit. Check for the following:
upload_max_filesize = xxM
post_max_size = xxM
I will include in the next update some additional functions for better error handling in the sample img_save_to_file.php and img_crop_to_file.php files
Cheers
Mat

**Comment by sconsult** [comment]
Latest Update from today should provide you feedback on the issue, when utilizing the Callback Method onError
Cheers
Mat
