### ISSUE TITLE
Is there a way to disable rotate?

### ISSUE THREAD

**Issue by drewbix** [sconsult/croppic#63]
Would be a nice addition - may open a pull request if not

**Comment by sconsult** [comment]
There was no thought on having a disable option for it, feel free to go ahead with the pull request.
this is something i would consider merging into the master.

Cheers

Mat

**Comment by sconsult** [comment]
hi drewbix,

Just released the latest version. You have now full control over which controls are displayed.
The site has been updated with an working example,

Cheers

Mat
