### ISSUE TITLE
Mobile Support Problem

### ISSUE THREAD

**Issue by shareefmoaryur** [sconsult/croppic#64]
Use touchit plugin to solve this issue..

https://github.com/danielglyde/TouchIt/

eg:
<script src="js/plugins/touchit/touchit.js"></script>
<script>
 var croppicOptions = {
        uploadUrl: 'xxxxxx',
        cropUrl: 'xxx',
        imgEyecandy: false,
        onAfterImgUpload:function(){$('.cropImgWrapper').touchit();}
    }
    var cropContainer= new Croppic('cropContainer', croppicOptions);
</script>

**Comment by sconsult** [comment]
will take a look at it
Thank you

**Comment by sconsult** [comment]
Hi shareefmoaryur,

Integrated drag support for mobile, will look into zoom capabillites through pinch in/ out. 

https://github.com/danielglyde/TouchIt/  has not been updated for 3 years so its probably not the best choice.

Cheers

Mat
