### ISSUE TITLE
Why i got this error?

### ISSUE THREAD

**Issue by rajlaksh** [sconsult/croppic#65]
This is error:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

that error show only on Cropping Images.

JS code is correct.

**Comment by sconsult** [comment]
Which version did you download ? And from where ?

Mat

**Comment by sconsult** [comment]
I have updated the downloadables, please try to redownload croppic.

The error your are receiving is handled in the latest version. You most likely either have no access to the directory (permissions) or you are trying to upload a picture which is larger then what your webserver settings (php.ini) are allowing.

Try the latest version and let me know if one of the items above help you solve the issue.

Cheers

Mat

**Comment by rajlaksh** [comment]
Problem solved. Crop php file didn't work correctly. Upload Path  Problem.
after that it works correctly.

**Comment by sconsult** [comment]
glad you resolved the isse.
