### ISSUE TITLE
onError is not triggered if other triggers are specified

### ISSUE THREAD

**Issue by newtonianb** [sconsult/croppic#70]
I make use of ``onAfterImgCrop`` and I wanted to also handle ``onError`` however when I specify ``onAfterImgCrop`` then ``onError`` is never triggered.

**Comment by sconsult** [comment]
hi @newtonianb 

Can you elaborate on the onError Feedback you would expect in your scenario?

Your stating : " I specify onAfterImgCrop then onError is never triggered". This is code wise not possible. If there is a error, onError will be called before onAfterImgCrop.

when you look into the coding segment withint croppic.js around line 579 (where the response of the croppic is handled) you will see at line 595 the following code.

---------------------------------------------------------------------------------------
if(response.status=='error'){
        if (that.options.onError) that.options.onError.call(that,response.message);
		that.hideLoader();
		setTimeout( function(){ that.reset(); },2000)											
	}
					
if (that.options.onAfterImgCrop) that.options.onAfterImgCrop.call(that);

---------------------------------------------------------------------------------------

This handles first the scenario of a problem with the fileupload or cropping failure, and after that the 
onAfterImgCrop is called. onError is only called if there was an error.

onErrors provides feedback about a series of problems, such as picture to large for upload, permission issues preventing an upload, crop could not be performed etc.

I hope this clearifies your question. if not please dont hesitate to add more details to what it is your trying to achieve, some code examples and your expectations what should happen ;-)

Cheers

Mat

**Comment by sconsult** [comment]
By the way, you can test this if you are going to croppic.net, open the console and try to upload a large picture 1.5 mb and up. you will see in the console the following output.

(index):564 onBeforeImgUpload
(index):570 onError:something went wrong, most likely file is to large for upload. check upload_max_filesize, post_max_size and memory_limit in you php.ini

Cheers

Mat

**Comment by newtonianb** [comment]
Hi Mat, thank you for your answer. I just ran a couple more tests and I can't quite reproduce my original problem, it might have been a miscompiled coffeescript issue. I will re-open if it re-happens thank you for your time!
