### ISSUE TITLE
Allow a new upload when loaded image exists

### ISSUE THREAD

**Issue by Mat-Moo** [sconsult/croppic#71]
If you use the loadPicture option, the ability to upload a new image is then removed. The simple solution is to add that.bindImgUploadControl() after the that.loadExistingImage(), perhaps via an option?

**Comment by sconsult** [comment]
Hi Mat-Moo,

Thank you for your input.

The simple solution for what you would like to achieve is just to reinitialize croppic with new loadPicture Option. You can utilize the Callbacks to decide when the re initialization should happen.
  
The intend for loadPicture is to avoid an upload in the first place and is targeted to improve integration capabilities for systems who have the images already on the server.

Hope that helps

Mat

**Comment by Mat-Moo** [comment]
Maybe this ties in with #72 then in, and I'm trying to use it in the wrong way, just not expected behaviour from what I expected.
