### ISSUE TITLE
loadPicture scaling

### ISSUE THREAD

**Issue by Mat-Moo** [sconsult/croppic#72]
When you pre-load a picture (e.g. a users selected avatar) it would be nice to turn off the scaling in the initialScaleImg function, otherwise once the user uploads and crops an avatar (for my purpose) then comes in again, the original image is correct but shown scaled up.

**Comment by sconsult** [comment]
i am not sure if i understand correctly what you are trying to achieve here.
There is an option scaleToFill which is used in the zoom function. initialScaleImg  calls this zoom function within. Is this what your looking for ?

**Comment by Mat-Moo** [comment]
initialScaleImg:function(){
var that = this;
that.zoom(-that.imgInitW);
that.zoom(40);

that.zoom(40) - If I'm loading an already existing cropped image, I don't want to scale it. I guess I need to create an image to load the current one, and offer an option to replace it, where it hides my image,. and init's yours but blank and not preloaded. What I'm trying to achieve is to use your plugin to allow people to see and replace their current avatar on my system

**Comment by sconsult** [comment]
Would you be interested to make a pull request and add it to the tool?  I’m always open to add new options to the tool as long as it brings the tool forward and provides backwards compatibility.

I am in the middle of a new software release, so my time is right now limited.

Adding a noScale:false option which get handled in the initScale could certainly work.

Cheers

Mat
