### ISSUE TITLE
init upload click on placeholder.png

### ISSUE THREAD

**Issue by Pohalo** [sconsult/croppic#75]
Thank you for this nice tool!
Is is possible to use the placholder image for initialising the upload dialog?
If i try this to trigger upload:
>$( "#croppic" ).on( "click", function() {
			$("#uploadButton").trigger('click');
});</addr>

i get a "too much recursion" jquery error.
Do you have any ideas?

**Comment by sconsult** [comment]
Hi Pohalo,

You might want to look at this older pull request, for what you are trying to achieve.

https://github.com/sconsult/croppic/pull/22, looking at the code i think its exactly what you need.

too much recursion indicates that the the function eventually call itself and is therefore in a loop.
Without seeing the whole code its almost impossible to give you any pointers.

Cheers

Mat

**Comment by Pohalo** [comment]
Hi Mat,

 

thank you this works!

 

Greetings

Peter

 

Von: Mat Steinlin [mailto:notifications@github.com] 
Gesendet: Freitag, 20. Februar 2015 14:09
An: sconsult/croppic
Cc: Pohalo
Betreff: Re: [croppic] init upload click on placeholder.png (#75)

 

Hi Pohalo,

You might want to look at this older pull request, for what you are trying to achieve.

#22 <https://github.com/sconsult/croppic/pull/22> , looking at the code i think its exactly what you need.

too much recursion indicates that the the function eventually call itself and is therefore in a loop.
Without seeing the whole code its almost impossible to give you any pointers.

Cheers

Mat
