### ISSUE TITLE
IE9 support or fallback

### ISSUE THREAD

**Issue by asso1985** [sconsult/croppic#76]
Is there anyway to have IE9 support or fallback ?

Can help if needed.

**Comment by sconsult** [comment]
it is in work right now. I would anticipate it being updated by the end of the month

Mat

**Comment by sconsult** [comment]
@asso1985 there goes my deployment plan, just got involved in anther project and my expected downtime is now gone. I will not be able to work on it this next couple weeks.
if your interested to get this done, just make a pull request.
User: martinlingstuyl  has already taken a stab at it, you might want to work of this basis.

https://github.com/sconsult/croppic/pull/30

Let me know if your interested to make this contribution

Cheers

Mat

**Comment by ataravati** [comment]
Any update on this?

**Comment by sconsult** [comment]
unfortunately have not heard back from @asso1985. I will get to that at the next oppurtunity

**Comment by ataravati** [comment]
Thanks!

**Comment by nutandevjoshi** [comment]
@sconsult Hi , you said on Feb 19 you will give IE9 support. Its still not IE9 compatible. Any updates on it ? Can you please implement IE9 support in your plugin ? Thanks.

**Comment by sconsult** [comment]
Hi @nutandevjoshi 

if you read the whole thread i also said i have not time for it right now ;-) 

However you can implement it with some modifications from here:

https://github.com/sconsult/croppic/pull/30

It just not out of the box just yet.

Hope this helps to get you started until its implemented and merged into the master.

Cheers,

Mat

**Comment by asso1985** [comment]
No time at all man sorry! Crazy period at work ;)

**Comment by sconsult** [comment]
I got finally around to it. IE9 support has been added, its not yet tested in IE8.
A little snag: Keep please in mind inlineProcessing (FileReader API) is available only from IE10+. For that case i have added an error output that this is not supported.
Other then that you should be fine now

**Comment by ataravati** [comment]
Thanks, Mat! :+1:

**Comment by nutandevjoshi** [comment]
Thanks developers :)
