### ISSUE TITLE
Crop Time

### ISSUE THREAD

**Issue by shikharsaxena727** [sconsult/croppic#81]
At times, cropping of large images takes minutes on my website when I use croppic. The same happens many a times when I crop large images on the Croppic website itself. The loading gif after the crop stays there for a lot of time. Any solution?

**Comment by sconsult** [comment]
Asuming you have a default installation and use our sample scripts, the best pointer i can give you without looking at yout enviroment are server resources (memory/cpu) or bandwith Issues (connectivity to the server).

if you can more information about your enviroment, i will certainly try to help you.

Mat

**Comment by sconsult** [comment]
No feedback received..Closing Issue
