### ISSUE TITLE
Way to use croppic in Laravel

### ISSUE THREAD

**Issue by chon27** [sconsult/croppic#82]
Hello,
I'm using this plugin and I'm having problems in Laravel. When I select my file (image) it is not preload correctly, the path of url is wrong. This is my structure:
www.mydomain.com/blog/newpost

The url given is relative:
temp/myimage
and it is searched at:
www.mydomain.com/blog/temp/myimage
when it is at:
www.mydomain.com/temp/myimage

I could fix that only appending a path to temp routes in javascript code I think, but I don't know how to do it. 
How could I solve that?

Thank you.

**Comment by sconsult** [comment]
Hi there,

when you preload a picture you have to set the path as relative url to the picture:

loadPicture:'assets/img/night.jpg',

if your path is relative then you might use in your example:

loadPicture:'../templ/myimage',  

Full example from the website:

var croppicContainerPreloadOptions = {
				uploadUrl:'img_save_to_file.php',
				cropUrl:'img_crop_to_file.php',
				loadPicture:'assets/img/night.jpg',
				enableMousescroll:true,
				loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> '
		}
		var cropContainerPreload = new Croppic('cropContainerPreload',  croppicContainerPreloadOptions);


Just to add this as well destination files for file upload and file crop location you need modify the two files: 

img_save_to_file.php
-->  $imagePath = "temp/";


img_crop_to_file.php
-->$output_filename = "temp/croppedImg_".rand();

Cheers

Mat

**Comment by sconsult** [comment]
@chon27 

Where you able top fix your problem ?

Mat

**Comment by chon27** [comment]
Thank you very much but I am newbie at Laravel and I think I need more time for understanding this framework. Then I'll try again with it later.

Sorry for any inconvenience.
