### ISSUE TITLE
Plugin does not work nicely with files with non-image file types.

### ISSUE THREAD

**Issue by anik786** [sconsult/croppic#83]
The plugin does not seem to output correct messages when choosing a file of non-image file types (e.g. .pdf) . Instead it justs hangs!

What should happen is that it should allow the developer to display an error like "This is not an image".

Furthermore, the file chooser/ explorer should be limited to only show images rather than "all files".

Please fix & improve.

But great plugin none the less!

**Comment by sconsult** [comment]
Hi @anik786 

We are testing these improvements right now, however if you would like to participate in the project and add these features you would be more then welcome.

Cheers

Mat
