### ISSUE TITLE
Nodejs Implementation

### ISSUE THREAD

**Issue by tomalex0** [sconsult/croppic#87]
Is there any example based on nodejs?

**Comment by sconsult** [comment]
i have not played with nodejs so far sorry. anybody in the community ?

**Comment by tomalex0** [comment]
I started  trying out with node js
https://github.com/tomalex0/croppic/tree/nodejs

Only first part is done,

**Comment by sconsult** [comment]
hi @tomalex0 

I receive often requests for either nodejs or bower. have not made my mind up which one to support.
Keep up the good work, i will be watching your progress ;-)

Mat

**Comment by tomalex0** [comment]
I'm having hard time setting up ImageMagick in my windows  system. Do you have any pointers.
This is actually stopping my further progress

**Comment by sconsult** [comment]
hi @tomalex0

This is actually of topic for the current thread, i would kindly ask you to open a new issue for ImageMagick, and post some sample code, logs or anything specific so we can take a look where you get stuck with ImageMagick

Mat

**Comment by sconsult** [comment]
Hi @tomalex0

Bower has been implemented with the last update, we will currently not pursue any other implementation.

Mat

**Comment by tomalex0** [comment]
@sconsult 

I have partially updated my nodejs implementation, up to an extend cropping is working.
Rotate is not working as of now.

https://github.com/tomalex0/croppic/tree/nodejs
