### ISSUE TITLE
onAfterImgCrop Doesn't know if it was successful or not

### ISSUE THREAD

**Issue by Novocaine88** [sconsult/croppic#91]
I'm trying to use the `onAfterImgCrop` and `onError` callbacks to either show success messages or error messages.

Error messages are no problem, however success messages are not so simple. I presumed the callback `onAfterImgCrop` would either mean *yes it's successful* OR contain the response (like the `onError` callback does like so, making use of the error response.
```Javascript
onError: function(error) {
```

I'm trying the following code as a work around in the options object;

```JavaScript
onAfterImgCrop: function() {
	$('.up_success_msg_lrg').show();
},
onError: function(error) {
	$('.up_success_msg_lrg').hide();
}
```

But the `onError` function runs first, meaning I cannot hide the success message as it doesn't exist. I've also tried adding a `return false;` to the error, to no avail.

Am I missing something? If not, I think the easiest fix *might* be to send the response to the `onAfterImgCrop` callback in the same way it does for the `onError`

**Comment by sconsult** [comment]
Hi @Novocaine88 

Very good points and well taken. This is actually a lot of developers have requested, so they have the abillity to handle the response on their side.

This will be in one of the upcoming deployments,l however if you want to make a pull request and change the code accordingly the credit would go to you as a participator.

Let me know how you want to proceed

Mat

**Comment by Novocaine88** [comment]
I'm not bothered about making a pull request, as the changes I've made Include a load of formatting changes as per my own preference. However to get this working required very little to be changed;

This snippet
```JavaScript
if (that.options.onAfterImgCrop) {
	that.options.onAfterImgCrop.call(that);
}
```
Just needed `response.status` added as another attribute in the  `call()` function. This seection of code can be found here;

```JavaScript
$.ajax({
	url: that.options.cropUrl,
	data: formData,
	context: document.body,
	cache: false,
	contentType: false,
	processData: false,
	type: 'POST'
}).always(function(data) {
	response = typeof data == 'object' ? data : jQuery.parseJSON(data);
	
	if (response.status == 'success') {
		if (that.options.imgEyecandy)
			that.imgEyecandy.hide();
		
		that.destroy();
		
		that.obj.append('<img class="croppedImg" src="' + response.url + '">');
		if (that.options.outputUrlId !== '') {
			$('#' + that.options.outputUrlId).val(response.url);
		}
		
		that.croppedImg = that.obj.find('.croppedImg');

		that.init();
		
		that.hideLoader();

	}
	if (response.status == 'error') {
		if (that.options.onError) {
			that.options.onError.call(that, response.message);
		}
		that.hideLoader();
		setTimeout(function() { that.reset(); }, 2000);
	}
	
	if (that.options.onAfterImgCrop) {
		that.options.onAfterImgCrop.call(that, response.status); // <-------------
	}

});
```
