### ISSUE TITLE
Don't want to auto resize image after upload...

### ISSUE THREAD

**Issue by anannx** [sconsult/croppic#92]
I want after images uploaded it keep its original size even it smaller than the container and when drag I can drag it to any position, not limit align to border of container, then when crop if missing area will be filled with solid color as in picture
![example](https://cloud.githubusercontent.com/assets/11972021/7173928/ae84ef34-e429-11e4-85a0-f883f985fb5a.png)
Thanks for help me.

**Comment by sconsult** [comment]
if i understand your request correctly, the easiest way for you to achieve this would be:

1.) rewrite the zoom function:   zoom :function(x)  to your liking, currently it doesnt allow to go smaller then the object hight.
2.) the background is another story, depending where you want to make the change and assuming that you are using the sample php files. I would suggest you add the color within php.

By default, (and you can see that if you simply rotate an image, so the corner are not within the image) the background is held white in frontend, and blackend when your crop it.

**Comment by sconsult** [comment]
i have added some example code in Issue: #92

This might help you

Mat

**Comment by sconsult** [comment]
Hi @anannx 

@leocorder has shared his implementation https://github.com/sconsult/croppic/issues/92. It should be suitable for your needs as well.

Cheers

Mat

**Comment by jamienk** [comment]
It's in #100 not 92 which is this issue :)
