### ISSUE TITLE
Preload picture with upload controls

### ISSUE THREAD

**Issue by ataravati** [sconsult/croppic#94]
Hi,

Is there anyway I can pre-load a picture into the widget and show the upload controls instead of the crop ones? I think this scenario is a lot more common when there's an existing image that has been uploaded and cropped before, and you just want to the option to upload a new one to replace it with. But, when you use the loadPicture property to pre-load a picture, the crop controls will appear on the widget.

Thanks,
Ali

**Comment by sconsult** [comment]
Hi @ataravati,

Thank you for your input. As you have stated correctly loadPicture has a certain functionality and does not do what you would like to have.

The Request you are actually asking for has been implemented by @diandsonc
You can find his excellent work here: https://github.com/sconsult/croppic/pull/22

I think you should be able to adjust the code to your needs, as it allows you to load picture with upload controls.

Mat

**Comment by ataravati** [comment]
Thank you, @sconsult! That's exactly what I needed.

**Comment by sconsult** [comment]
Glad to hear, good luck ;-)

Mat
