### ISSUE TITLE
Laptop + touch screen not supported

### ISSUE THREAD

**Issue by 212070170** [sconsult/croppic#95]
I was trying to test the code on a touchscreen laptop and the image drag was not working, although it works well on Ipad and regular laptops. I have modified the code slightly to fix the issue but i still  wanted to document it here. 

what i did was replace lines 419 and 439 of croppic.js from
                if (userAgent.match(/iPad/i) || userAgent.match(/iPhone/i) || userAgent.match(/android/i)) {
to
                if (userAgent.match(/iPad/i) || userAgent.match(/iPhone/i) || userAgent.match(/android/i) || e.pageY == undefined) {

Adding the condition to account for being touch but still not having an IOS user agent.

**Comment by sconsult** [comment]
Hi 212070170,

Thank you for reporting the problem and providing a fix. We have 2 options here:

1.) i integrate your fix after testing and take all the credit ;-)
2.) create a pull request, add the fix and i will merge it with the master so the credit goes where it belongs.

How do you want me to handle it?

Once again, thank you for helping making croppic an excellent and all around compatible plugin.

Mat

**Comment by 212070170** [comment]
I submitted a pull request. Thanks for replying

**Comment by sconsult** [comment]
hey...credit where credit is due. i want contributors being recognized appropriately ;-)

Thanks again

Mat
