### ISSUE TITLE
wrong aspect ratio

### ISSUE THREAD

**Issue by mrmagcore** [sconsult/croppic#98]
When I upload an image, the width and height are correctly returned by the server.  However, the tool displays the image stretched vertically.  When I zoom, it increases the height but not the width.  This is with a clean install with no changes that I can find

![screen shot 2015-05-08 at 11 14 24 am](https://cloud.githubusercontent.com/assets/858728/7542670/a76a8ab4-f573-11e4-863e-3c53b47d9168.png)

**Comment by mrmagcore** [comment]
Figured it out.  It's a conflict with foundation's css.  Took me a while, so I'll leave this here if anyone else has this problem.  Foundation sets images to have max-width of 100% unless overridden.

**Comment by sconsult** [comment]
Could you post the conflicting css section and your correction? I'm not sure I can either replicate the issue nor follow your outline.

Appreciate the feedback
Mat

**Comment by mrmagcore** [comment]
line 2892 of foundation.css:

  img {
    max-width: 100% !important; }


it's fine, to fix all you need to do is override this for the image in the croppic tool

**Comment by tobalsan** [comment]
Ah, thank you! 
FYI, I had the same problem with Bootstrap 4.
